# Generated by Django 5.2.17 on 2026-08-30 09:20
# ============================================================
# MARKETPULSE - INITIAL RISK SNAPSHOT DATABASE MIGRATION
# Purpose: Define the first database structure for RiskSnapshot.
# Framework: Django models → Migration operations → Database.
# Lecture: Imports, inheritance, variables, lists, tuples,
# dictionaries, keyword arguments, data types and relationships.
# ============================================================
# 1. IMPORTS
# ============================================================
import django.db.models.deletion  # I import Django's related-object deletion rules.
from django.conf import settings  # I import access to the project's configured settings.
from django.db import migrations, models  # I import migration operations and model field classes.
# ============================================================
# 2. MIGRATION CLASS AND INITIAL STATUS
# ============================================================
class Migration(migrations.Migration):  # I inherit Django's migration behaviour in this class.
    initial = True  # I use a Boolean to mark this as an initial migration.
    # ========================================================
    # 3. DEPENDENCY: CONFIGURED USER MODEL
    # ========================================================
    dependencies = [  # I begin the list of migrations that must come first.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # I depend on the initial migration of the configured user model's app.
    ]  # I finish the dependency list.
    # ========================================================
    # 4. DATABASE OPERATIONS
    # ========================================================
    operations = [  # I begin the ordered list of schema operations.
        migrations.CreateModel(  # I declare an operation that creates this model's database table.
            name='RiskSnapshot',  # I give the model its recorded name.
            # ================================================
            # 4.1 FIELD DEFINITIONS
            # ================================================
            fields=[  # I begin a list of tuples pairing field names with field objects.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # I define an automatic 64-bit primary key; serialize=False excludes it from model serialization.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # I define a timestamp automatically set when a record is first saved.
                ('updated_at', models.DateTimeField(auto_now=True)),  # I define a timestamp automatically refreshed during normal model saves.
                ('symbol', models.CharField(blank=True, max_length=20)),  # I define text up to 20 characters and allow it to be blank during validation.
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=14)),  # I define a decimal with 14 total digits, including 2 after the decimal point.
                ('risk_percentage', models.DecimalField(decimal_places=6, max_digits=8)),  # I define a decimal with 8 total digits, including 6 after the decimal point.
                ('volatility', models.DecimalField(decimal_places=6, default=0, max_digits=10)),  # I define a decimal with 10 total digits, 6 decimal places and a model default of zero.
                ('recommended_position_size', models.DecimalField(decimal_places=4, max_digits=14)),  # I define the position-size value with 14 total digits and 4 decimal places.
                ('stop_loss_price', models.DecimalField(decimal_places=4, max_digits=14)),  # I define the stop price with 14 total digits and 4 decimal places.
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to=settings.AUTH_USER_MODEL)),  # I link each snapshot to a user; Django cascades user deletion to snapshots, and user.risk_snapshots provides reverse access.
            ],  # I finish the field-definition list.
            # ================================================
            # 4.2 MODEL OPTIONS
            # ================================================
            options={  # I begin a dictionary of recorded model settings.
                'abstract': False,  # I mark this as a concrete model with its own database table.
            },  # I finish the options dictionary.
        ),  # I finish the CreateModel operation.
    ]  # I finish the migration's operations list.