# Generated by Django 5.2.17 on 2026-08-30 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('risk_percentage', models.DecimalField(decimal_places=6, max_digits=8)),
                ('volatility', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('recommended_position_size', models.DecimalField(decimal_places=4, max_digits=14)),
                ('stop_loss_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
