# Generated by Django 5.2.17 on 2026-08-30

# ============================================================
# CORE - INITIAL DATABASE MIGRATION
# ============================================================
# PURPOSE:
# This is the first migration for the core Django application.
# It tells Django how to create the first database structure
# for Alert, MarketData, Strategy, and Backtest.
#
# FRAMEWORK:
# Django 5.2 Migration Framework
#
# FRAMEWORK FLOW:
#
# core/models.py
#     ↓
# python manage.py makemigrations
#     ↓
# core/migrations/0001_initial.py
#     ↓
# Django Migration Framework
#     ↓
# python manage.py migrate
#     ↓
# Django SchemaEditor
#     ↓
# PostgreSQL / Neon Database
#
# MODEL RELATIONSHIPS:
#
# AUTH_USER_MODEL
#     ↓
# Alert
#
# AUTH_USER_MODEL
#     ↓
# Strategy
#     ↓
# Backtest
#
# MarketData
#     ↓
# Stores unique symbol + date market observations
#
# PROGRAMMING LANGUAGE FEATURES / CONCEPTS:
#
# Imports              -> reuse code from Django modules
# Class                 -> Migration defines a migration object
# Inheritance           -> Migration inherits migrations.Migration
# Variables             -> initial, dependencies, operations
# Assignment            -> = stores values in variables
# Boolean               -> True and False
# Lists                 -> ordered collections using [ ]
# Tuples                -> grouped values using ( )
# Dictionaries          -> key/value collections using { }
# Strings               -> text such as 'Alert' and 'symbol'
# Function calls        -> swappable_dependency(...)
# Object creation       -> models.CharField(...), CreateModel(...)
# Keyword arguments     -> max_length=20, default=False
# Database types        -> CharField, DateField, DecimalField, etc.
# Relationships         -> ForeignKey connects database models
# Constraints           -> UniqueConstraint protects data integrity
# OOP                   -> Django classes and model-field objects
# ============================================================

# ============================================================
# 1. IMPORTS
# ============================================================

import django.db.models.deletion  # Imports Django's database deletion behaviours such as CASCADE.
from django.conf import settings  # Imports the project's Django settings so this migration can use AUTH_USER_MODEL.
from django.db import migrations, models  # Imports Django migration tools and database model field classes.

# ============================================================
# 2. MIGRATION CLASS
# ============================================================

class Migration(migrations.Migration):  # Defines the Migration class and inherits Django's Migration behaviour.
    initial = True  # Boolean value telling Django that this is an initial migration.
    dependencies = [  # Creates a list containing migrations that must exist before this migration runs.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Makes this migration depend on the configured Django User model.
    ]  # Ends the dependencies list.

# ============================================================
# 3. DATABASE OPERATIONS
# ============================================================

    operations = [  # Creates a list of database operations Django must perform.

# ============================================================
# 4. CREATE ALERT MODEL
# ============================================================

        migrations.CreateModel(  # Creates the Alert model and its database table.
            name='Alert',  # String argument giving the new model the name Alert.
            fields=[  # Starts a list containing the database fields for Alert.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Tuple defining the automatic primary-key ID field.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Stores the date and time when an Alert is first created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Stores the date and time whenever an Alert is updated.
                ('alert_type', models.CharField(choices=[('price', 'Price'), ('strategy', 'Strategy'), ('risk', 'Risk'), ('regime', 'Market Regime')], max_length=20)),  # Stores an alert category selected from the allowed choices.
                ('title', models.CharField(max_length=200)),  # Stores the short title of the alert as text.
                ('message', models.TextField()),  # Stores the longer alert message as text.
                ('is_read', models.BooleanField(default=False)),  # Boolean field recording whether the user has read the alert.
                ('is_active', models.BooleanField(default=True)),  # Boolean field recording whether the alert is currently active.
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),  # Creates a many-to-one relationship from Alert to the configured User model.
            ],  # Ends the Alert fields list.
            options={  # Starts a dictionary containing model configuration options.
                'abstract': False,  # States that Alert is a real database model rather than an abstract base model.
            },  # Ends the Alert options dictionary.
        ),  # Ends the CreateModel operation for Alert.

# ============================================================
# 5. CREATE MARKETDATA MODEL
# ============================================================

        migrations.CreateModel(  # Creates the MarketData model and its database table.
            name='MarketData',  # String argument giving the new model the name MarketData.
            fields=[  # Starts a list containing the database fields for MarketData.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Tuple defining the automatic primary-key ID field.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Stores when this market-data record was first created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Stores when this market-data record was last updated.
                ('symbol', models.CharField(db_index=True, max_length=20)),  # Stores the ticker symbol and creates a database index for faster searches.
                ('date', models.DateField(db_index=True)),  # Stores the market-data date and creates an index for faster date searches.
                ('open_price', models.DecimalField(decimal_places=4, max_digits=14)),  # Stores the opening price using fixed decimal precision.
                ('high_price', models.DecimalField(decimal_places=4, max_digits=14)),  # Stores the highest price using fixed decimal precision.
                ('low_price', models.DecimalField(decimal_places=4, max_digits=14)),  # Stores the lowest price using fixed decimal precision.
                ('close_price', models.DecimalField(decimal_places=4, max_digits=14)),  # Stores the closing price using fixed decimal precision.
                ('volume', models.BigIntegerField(default=0)),  # Stores the trading volume as a large integer with zero as its default.
            ],  # Ends the MarketData fields list.
            options={  # Starts a dictionary containing MarketData configuration options.
                'ordering': ['-date'],  # Uses a list to order MarketData records by newest date first.
                'constraints': [models.UniqueConstraint(fields=('symbol', 'date'), name='unique_symbol_date')],  # Prevents duplicate records for the same symbol and date combination.
            },  # Ends the MarketData options dictionary.
        ),  # Ends the CreateModel operation for MarketData.

# ============================================================
# 6. CREATE STRATEGY MODEL
# ============================================================

        migrations.CreateModel(  # Creates the Strategy model and its database table.
            name='Strategy',  # String argument giving the new model the name Strategy.
            fields=[  # Starts a list containing the database fields for Strategy.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Tuple defining the automatic primary-key ID field.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Stores when the Strategy was first created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Stores when the Strategy was last updated.
                ('name', models.CharField(max_length=120)),  # Stores the strategy name as text with a maximum length of 120 characters.
                ('description', models.TextField(blank=True)),  # Stores an optional longer description of the strategy.
                ('is_active', models.BooleanField(default=True)),  # Boolean field recording whether the strategy is active.
                ('rule_config', models.JSONField(default=dict)),  # Stores flexible strategy configuration data as JSON using an empty dictionary by default.
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),  # Creates a many-to-one relationship from Strategy to the configured User model.
            ],  # Ends the Strategy fields list.
            options={  # Starts a dictionary containing Strategy configuration options.
                'abstract': False,  # States that Strategy is a real database model rather than an abstract base model.
            },  # Ends the Strategy options dictionary.
        ),  # Ends the CreateModel operation for Strategy.

# ============================================================
# 7. CREATE BACKTEST MODEL
# ============================================================

        migrations.CreateModel(  # Creates the Backtest model and its database table.
            name='Backtest',  # String argument giving the new model the name Backtest.
            fields=[  # Starts a list containing the database fields for Backtest.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Tuple defining the automatic primary-key ID field.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Stores when the Backtest was first created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Stores when the Backtest was last updated.
                ('symbol', models.CharField(max_length=20)),  # Stores the market ticker symbol used for the backtest.
                ('start_date', models.DateField()),  # Stores the starting date of the backtest period.
                ('end_date', models.DateField()),  # Stores the ending date of the backtest period.
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000, max_digits=14)),  # Stores the amount of capital available at the start of the backtest.
                ('final_capital', models.DecimalField(decimal_places=2, default=0, max_digits=14)),  # Stores the amount of capital remaining at the end of the backtest.
                ('total_return', models.DecimalField(decimal_places=6, default=0, max_digits=10)),  # Stores the calculated overall return from the backtest.
                ('max_drawdown', models.DecimalField(decimal_places=6, default=0, max_digits=10)),  # Stores the calculated maximum decline from a previous portfolio peak.
                ('sharpe_ratio', models.DecimalField(decimal_places=6, default=0, max_digits=10)),  # Stores the calculated Sharpe ratio performance measurement.
                ('win_rate', models.DecimalField(decimal_places=6, default=0, max_digits=10)),  # Stores the proportion of successful trades from the backtest.
                ('total_trades', models.PositiveIntegerField(default=0)),  # Stores the total number of trades as a non-negative integer.
                ('transaction_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),  # Stores the transaction costs generated during the backtest.
                ('results', models.JSONField(default=dict)),  # Stores flexible detailed backtest result data as JSON.
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='core.strategy')),  # Creates a many-to-one relationship connecting each Backtest to a Strategy.
            ],  # Ends the Backtest fields list.
            options={  # Starts a dictionary containing Backtest configuration options.
                'abstract': False,  # States that Backtest is a real database model rather than an abstract base model.
            },  # Ends the Backtest options dictionary.
        ),  # Ends the CreateModel operation for Backtest.
    ]  # Ends the complete list of migration operations.