# ============================================================
# CORE MIGRATION 0002
# ============================================================
# File:
# core/migrations/0002_alter_alert_options_alter_backtest_options_and_more.py
#
# WHAT THIS FILE IS FOR:
# This migration records database changes made after 0001_initial.
#
# It changes:
# - Alert ordering
# - Backtest ordering
# - Strategy ordering
# - Alert fields
# - Alert choices
# - Alert database uniqueness rules
#
# DJANGO FRAMEWORK FLOW:
#
# core/models.py
#     ↓
# python manage.py makemigrations
#     ↓
# This migration file
#     ↓
# python manage.py migrate
#     ↓
# PostgreSQL / Neon
#
# PROGRAMMING LANGUAGE CONCEPTS USED:
# - Modules and imports
# - Classes
# - Inheritance
# - Variables / class attributes
# - Lists
# - Tuples
# - Dictionaries
# - Strings
# - Boolean values
# - Function and constructor calls
# - Positional arguments
# - Keyword arguments
# - Nested expressions
# - Object composition
#
# DJANGO CONCEPTS USED:
# - Migration
# - Migration dependencies
# - Model Meta options
# - ORM model fields
# - Database indexes
# - JSON fields
# - Nullable fields
# - Field choices
# - Q objects
# - Conditional UniqueConstraint
# ============================================================

# ============================================================
# 1. DJANGO GENERATED INFORMATION
# ============================================================

# Generated by Django 5.2.17 on 2026-09-04 16:06  # Django generated this migration automatically after detecting model changes.

# ============================================================
# 2. IMPORTS
# ============================================================

from django.conf import settings  # IMPORT: gets Django project settings, including the configured user model.
from django.db import migrations, models  # IMPORT: gets Django's migration system and database model classes.

# ============================================================
# 3. MIGRATION CLASS
# ============================================================

class Migration(migrations.Migration):  # CLASS + INHERITANCE: creates this migration by inheriting Django's Migration class.

    # ========================================================
    # 4. MIGRATION DEPENDENCIES
    # ========================================================
    # Dependencies tell Django what must exist before this
    # migration is allowed to run.
    # ========================================================

    dependencies = [  # LIST: stores the migrations that must run before this migration.
        ('core', '0001_initial'),  # TUPLE: says core migration 0001_initial must already have run.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # FUNCTION CALL: adds a dependency on the configured Django user model.
    ]  # Ends the dependencies list.

    # ========================================================
    # 5. MIGRATION OPERATIONS
    # ========================================================
    # Operations describe the database/model changes Django
    # must apply when this migration runs.
    # ========================================================

    operations = [  # LIST: stores all migration operations in the order Django should process them.

        # ====================================================
        # 5.1 ALTER ALERT MODEL OPTIONS
        # ====================================================

        migrations.AlterModelOptions(  # CONSTRUCTOR CALL: changes Meta options belonging to the Alert model.
            name='alert',  # KEYWORD ARGUMENT + STRING: identifies the Alert model.
            options={'ordering': ['-created_at']},  # DICTIONARY + LIST: newest alerts should be returned first by default.
        ),  # Ends the Alert AlterModelOptions operation.

        # ====================================================
        # 5.2 ALTER BACKTEST MODEL OPTIONS
        # ====================================================

        migrations.AlterModelOptions(  # CONSTRUCTOR CALL: changes Meta options belonging to the Backtest model.
            name='backtest',  # KEYWORD ARGUMENT + STRING: identifies the Backtest model.
            options={'ordering': ['-created_at']},  # DICTIONARY + LIST: newest backtests should be returned first by default.
        ),  # Ends the Backtest AlterModelOptions operation.

        # ====================================================
        # 5.3 ALTER STRATEGY MODEL OPTIONS
        # ====================================================

        migrations.AlterModelOptions(  # CONSTRUCTOR CALL: changes Meta options belonging to the Strategy model.
            name='strategy',  # KEYWORD ARGUMENT + STRING: identifies the Strategy model.
            options={'ordering': ['name']},  # DICTIONARY + LIST: strategies should be ordered alphabetically by name.
        ),  # Ends the Strategy AlterModelOptions operation.

        # ====================================================
        # 5.4 ADD ALERT ACTION URL
        # ====================================================

        migrations.AddField(  # CONSTRUCTOR CALL: adds a new database field to an existing model.
            model_name='alert',  # KEYWORD ARGUMENT + STRING: tells Django this field belongs to Alert.
            name='action_url',  # KEYWORD ARGUMENT + STRING: sets the new field name.
            field=models.CharField(blank=True, max_length=500),  # OBJECT CREATION: creates an optional text field with a maximum of 500 characters.
        ),  # Ends the action_url AddField operation.

        # ====================================================
        # 5.5 ADD ALERT KEY
        # ====================================================

        migrations.AddField(  # CONSTRUCTOR CALL: adds another field to the Alert model.
            model_name='alert',  # STRING: identifies Alert as the model being changed.
            name='alert_key',  # STRING: names the new field alert_key.
            field=models.CharField(blank=True, db_index=True, max_length=160),  # FIELD OBJECT: creates optional text and adds a database index for faster lookups.
        ),  # Ends the alert_key AddField operation.

        # ====================================================
        # 5.6 ADD ALERT METADATA
        # ====================================================

        migrations.AddField(  # CONSTRUCTOR CALL: adds a field to Alert.
            model_name='alert',  # STRING: identifies the Alert model.
            name='metadata',  # STRING: names the field metadata.
            field=models.JSONField(blank=True, default=dict),  # FIELD OBJECT: stores structured JSON data and uses an empty dictionary as its default.
        ),  # Ends the metadata AddField operation.

        # ====================================================
        # 5.7 ADD ALERT RESOLVED DATE/TIME
        # ====================================================

        migrations.AddField(  # CONSTRUCTOR CALL: adds another database column to Alert.
            model_name='alert',  # STRING: identifies the Alert model.
            name='resolved_at',  # STRING: names the field resolved_at.
            field=models.DateTimeField(blank=True, null=True),  # FIELD OBJECT: stores a date/time but allows the value to be empty or NULL.
        ),  # Ends the resolved_at AddField operation.

        # ====================================================
        # 5.8 ADD ALERT SEVERITY
        # ====================================================

        migrations.AddField(  # CONSTRUCTOR CALL: adds the severity field to Alert.
            model_name='alert',  # STRING: identifies Alert as the target model.
            name='severity',  # STRING: gives the new field its Python/database name.
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'High Priority')], default='info', max_length=20),  # FIELD + LIST + TUPLES: restricts severity to four choices and defaults to info.
        ),  # Ends the severity AddField operation.

        # ====================================================
        # 5.9 ALTER ALERT TYPE
        # ====================================================

        migrations.AlterField(  # CONSTRUCTOR CALL: changes the definition of an existing model field.
            model_name='alert',  # STRING: identifies the Alert model.
            name='alert_type',  # STRING: identifies the existing alert_type field.
            field=models.CharField(choices=[('price', 'Price'), ('data', 'Data'), ('strategy', 'Strategy'), ('risk', 'Risk'), ('stress', 'Stress Test'), ('regime', 'Market Regime'), ('system', 'System')], max_length=20),  # FIELD + CHOICES: limits alert_type to the supported MarketPulse alert categories.
        ),  # Ends the alert_type AlterField operation.

        # ====================================================
        # 5.10 ADD DATABASE UNIQUE CONSTRAINT
        # ====================================================
        # This protects the database from creating duplicate
        # active alerts with the same alert_key for one user.
        #
        # In simple words:
        #
        # Same user
        #     +
        # Same alert_key
        #     +
        # Alert is active
        #     +
        # alert_key is not empty
        #     ↓
        # Only ONE matching alert is allowed.
        # ====================================================

        migrations.AddConstraint(  # CONSTRUCTOR CALL: adds a database-level rule to the Alert model.
            model_name='alert',  # STRING: identifies Alert as the model receiving the constraint.
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('alert_key', ''), _negated=True)), fields=('user', 'alert_key'), name='unique_active_alert_key_per_user'),  # NESTED OBJECTS: creates conditional uniqueness for user + alert_key when the alert is active and alert_key is not empty.
        ),  # Ends the AddConstraint operation.
    ]  # Ends the complete migration operations list.