# Generated by Django 5.2.17 on 2026-09-04 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='backtest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='alert',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_key',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'High Priority')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('price', 'Price'), ('data', 'Data'), ('strategy', 'Strategy'), ('risk', 'Risk'), ('stress', 'Stress Test'), ('regime', 'Market Regime'), ('system', 'System')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('alert_key', ''), _negated=True)), fields=('user', 'alert_key'), name='unique_active_alert_key_per_user'),
        ),
    ]
