# Generated by Django 5.2.17 on 2026-09-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alert_options_alter_backtest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('price', 'Price'), ('data', 'Data'), ('strategy', 'Strategy'), ('risk', 'Risk'), ('stress', 'Stress Test'), ('regime', 'Market Condition'), ('system', 'System')], max_length=20),
        ),
    ]
