# ============================================================
# CORE MIGRATION 0003 - ALTER ALERT TYPE FIELD
# ============================================================
# Generated by Django 5.2.17 on 2026-09-05 16:46
# Django generated this migration automatically after a model change.
#
# PURPOSE:
# This migration changes the "alert_type" field in the Alert model.
#
# FRAMEWORK FLOW:
#
# core/models.py
#     ↓
# Alert model
#     ↓
# alert_type field
#     ↓
# python manage.py makemigrations
#     ↓
# This migration file
#     ↓
# python manage.py migrate
#     ↓
# Database schema
#
# PROGRAMMING LANGUAGE CONCEPTS USED:
#
# - Import statements
# - Classes
# - Inheritance
# - Variables
# - Lists
# - Tuples
# - Strings
# - Function / class calls
# - Keyword arguments
# - Nested data structures
# - Object-Oriented Programming
# ============================================================

# ============================================================
# 1. DJANGO IMPORTS
# ============================================================

from django.db import migrations, models  # IMPORT: brings Django migration and database-model tools into this Python file.

# ============================================================
# 2. MIGRATION CLASS
# ============================================================

class Migration(migrations.Migration):  # CLASS + INHERITANCE: creates Migration and inherits Django's Migration behaviour.
    # ========================================================
    # 3. MIGRATION DEPENDENCIES
    # ========================================================
    dependencies = [  # VARIABLE + LIST: stores the migration that must run before this migration.
        ('core', '0002_alter_alert_options_alter_backtest_options_and_more'),  # TUPLE + STRINGS: identifies the "core" app and previous migration.
    ]  # LIST: closes the dependencies list.

    # ========================================================
    # 4. DATABASE OPERATIONS
    # ========================================================
    operations = [  # VARIABLE + LIST: stores the database changes Django must perform.
        migrations.AlterField(  # CLASS/FUNCTION CALL: tells Django to modify an existing model field.
            model_name='alert',  # KEYWORD ARGUMENT + STRING: identifies the Alert model Django must change.
            name='alert_type',  # KEYWORD ARGUMENT + STRING: identifies the field being changed.
            field=models.CharField(choices=[('price', 'Price'), ('data', 'Data'), ('strategy', 'Strategy'), ('risk', 'Risk'), ('stress', 'Stress Test'), ('regime', 'Market Condition'), ('system', 'System')], max_length=20),  # OBJECT + LIST + TUPLES: defines a text field with allowed choices and a maximum length of 20 characters.
        ),  # FUNCTION/CALL CLOSURE: finishes the AlterField database operation.
    ]  # LIST: closes the migration operations list.