# Generated by Django 5.2.17 on 2026-09-06 20:22
# This comment tells us which Django version generated this migration and when.

# ============================================================
# CORE MIGRATION 0004 - CREATE ALERT RULE
# ============================================================
# FILE:
# core/migrations/0004_alertrule.py
#
# PURPOSE:
# This migration creates the database structure for AlertRule.
#
# MAIN FLOW:
#
# core/models.py
#     ↓
# AlertRule model
#     ↓
# python manage.py makemigrations
#     ↓
# This migration file
#     ↓
# python manage.py migrate
#     ↓
# Django Migration Framework
#     ↓
# PostgreSQL / Database
#     ↓
# AlertRule database table
#
# PROGRAMMING LANGUAGE CONCEPTS USED:
#
# - Imports and modules
# - Classes
# - Inheritance
# - Objects
# - Lists
# - Tuples
# - Dictionaries
# - Strings
# - Boolean values
# - Function / constructor calls
# - Positional and keyword arguments
# - Database field types
# - Primary keys
# - Foreign keys
# - Relationships
# - Constraints
# - Indexes
# - Object-Relational Mapping (ORM)
#
# IMPORTANT:
# This file defines a DATABASE SCHEMA CHANGE.
# It does not contain the business logic that checks market prices
# or decides when an alert should actually be triggered.

# ============================================================
# 1. IMPORTS
# ============================================================

import django.db.models.deletion  # IMPORT: Gives this migration access to Django database deletion behaviour such as CASCADE.
from django.conf import settings  # IMPORT: Gives access to Django project settings, including the configured custom user model.
from django.db import migrations, models  # IMPORT: Imports Django's migration system and database model field classes.

# ============================================================
# 2. MIGRATION CLASS
# ============================================================

class Migration(migrations.Migration):  # CLASS + INHERITANCE: Defines this migration and inherits Django's Migration behaviour.

    # ========================================================
    # 3. MIGRATION DEPENDENCIES
    # ========================================================
    # Dependencies tell Django which migrations must exist
    # before this migration is allowed to run.

    dependencies = [  # LIST: Stores the migrations that must run before this migration.
        ('core', '0003_alter_alert_alert_type'),  # TUPLE: Requires core migration 0003 to be completed first.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # FUNCTION CALL: Requires the currently configured Django user model because AlertRule has a user ForeignKey.
    ]  # LIST END: Finishes the migration dependency list.

    # ========================================================
    # 4. MIGRATION OPERATIONS
    # ========================================================
    # Operations describe what Django should change in
    # the database when this migration is applied.

    operations = [  # LIST: Stores the database operations performed by this migration.

        # ====================================================
        # 5. CREATE ALERT RULE MODEL
        # ====================================================

        migrations.CreateModel(  # OBJECT / CONSTRUCTOR CALL: Tells Django to create a new database model and corresponding table.
            name='AlertRule',  # KEYWORD ARGUMENT + STRING: Sets the Django model name to AlertRule.

            # =================================================
            # 6. ALERT RULE DATABASE FIELDS
            # =================================================
            # Each tuple contains:
            # ('field_name', Django field object)

            fields=[  # LIST: Contains all database fields belonging to the AlertRule model.

                # ------------------------------------------------
                # PRIMARY KEY
                # ------------------------------------------------

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # TUPLE + OBJECT: Creates an automatically increasing 64-bit integer primary key called id.

                # ------------------------------------------------
                # TIMESTAMP FIELDS
                # ------------------------------------------------

                ('created_at', models.DateTimeField(auto_now_add=True)),  # DATETIME FIELD: Automatically records when the AlertRule is first created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # DATETIME FIELD: Automatically records the latest time the AlertRule is updated.

                # ------------------------------------------------
                # MARKET SYMBOL FIELD
                # ------------------------------------------------

                ('symbol', models.CharField(db_index=True, help_text='US equity or ETF symbol monitored by this rule.', max_length=20)),  # STRING FIELD: Stores the market ticker such as SPY, AAPL, or MSFT and adds a database index for quicker searching.

                # ------------------------------------------------
                # METRIC FIELD
                # ------------------------------------------------

                ('metric', models.CharField(choices=[('price', 'Price'), ('volume', 'Volume'), ('percent_change', 'Percent Change'), ('volatility', 'Volatility')], default='price', max_length=30)),  # STRING + LIST + TUPLES: Stores which market measurement the alert should monitor and restricts it to predefined choices.

                # ------------------------------------------------
                # COMPARISON OPERATOR FIELD
                # ------------------------------------------------

                ('operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal')], default='gt', max_length=10)),  # STRING + CHOICES: Stores the comparison operation used when checking the metric against the threshold.

                # ------------------------------------------------
                # THRESHOLD FIELD
                # ------------------------------------------------

                ('threshold', models.DecimalField(decimal_places=6, help_text='Numeric threshold used when evaluating the rule.', max_digits=20)),  # DECIMAL FIELD: Stores the numeric value that the selected market metric is compared against.

                # ------------------------------------------------
                # OPTIONAL ALERT MESSAGE
                # ------------------------------------------------

                ('message', models.CharField(blank=True, help_text='Optional explanation displayed when the rule creates an alert.', max_length=255)),  # STRING FIELD: Stores an optional user-friendly explanation for the alert.

                # ------------------------------------------------
                # ENABLED / DISABLED STATE
                # ------------------------------------------------

                ('is_enabled', models.BooleanField(db_index=True, default=True)),  # BOOLEAN FIELD: Stores True or False to control whether this alert rule is currently active.

                # ------------------------------------------------
                # ALERT COOLDOWN
                # ------------------------------------------------

                ('cooldown_minutes', models.PositiveIntegerField(default=60, help_text='Minimum number of minutes before this rule may trigger another alert.')),  # INTEGER FIELD: Stores the minimum waiting period before the same rule can trigger another alert.

                # ------------------------------------------------
                # LAST TRIGGERED TIME
                # ------------------------------------------------

                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),  # DATETIME FIELD: Stores when the rule last triggered and allows the database value to be empty/null.

                # ------------------------------------------------
                # USER RELATIONSHIP
                # ------------------------------------------------

                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketpulse_alert_rules', to=settings.AUTH_USER_MODEL)),  # FOREIGN KEY: Connects each AlertRule to a user and deletes the user's rules if that user is deleted.
            ],  # LIST END: Finishes the AlertRule field definitions.

            # =================================================
            # 7. MODEL OPTIONS
            # =================================================
            # These options control how AlertRule records are
            # ordered and indexed by Django/database.

            options={  # DICTIONARY: Stores configuration options for the AlertRule model.

                # ------------------------------------------------
                # DEFAULT ORDERING
                # ------------------------------------------------

                'ordering': ['-is_enabled', 'symbol', 'metric', '-created_at'],  # LIST: Sorts enabled status descending, then symbol, metric, and newest creation date first.

                # ------------------------------------------------
                # DATABASE INDEX
                # ------------------------------------------------

                'indexes': [models.Index(fields=['user', 'symbol', 'is_enabled'], name='core_alertr_user_id_988078_idx')],  # INDEX: Creates a combined database index to improve queries using user, symbol, and enabled status together.
            },  # DICTIONARY END: Finishes the AlertRule model options.
        ),  # CREATE MODEL END: Finishes the CreateModel database operation.
    ]  # LIST END: Finishes all operations performed by migration 0004.