# Generated by Django 5.2.17 on 2026-09-06 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_alert_alert_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(db_index=True, help_text='US equity or ETF symbol monitored by this rule.', max_length=20)),
                ('metric', models.CharField(choices=[('price', 'Price'), ('volume', 'Volume'), ('percent_change', 'Percent Change'), ('volatility', 'Volatility')], default='price', max_length=30)),
                ('operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal')], default='gt', max_length=10)),
                ('threshold', models.DecimalField(decimal_places=6, help_text='Numeric threshold used when evaluating the rule.', max_digits=20)),
                ('message', models.CharField(blank=True, help_text='Optional explanation displayed when the rule creates an alert.', max_length=255)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('cooldown_minutes', models.PositiveIntegerField(default=60, help_text='Minimum number of minutes before this rule may trigger another alert.')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketpulse_alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_enabled', 'symbol', 'metric', '-created_at'],
                'indexes': [models.Index(fields=['user', 'symbol', 'is_enabled'], name='core_alertr_user_id_988078_idx')],
            },
        ),
    ]
