# Generated by Django 5.2.17 on 2026-08-30 09:20  # Django automatically created this migration file.

# ============================================================
# DATA MANAGEMENT - INITIAL DATABASE MIGRATION
# ============================================================
#
# PURPOSE:
#
# This is the first database migration for the
# data_management Django application.
#
# It creates the original database structure required for:
#
# 1. DataSource
#       Stores information about a market-data provider.
#
# 2. DataImport
#       Stores a record of each historical-data import job.
#
#
# FRAMEWORK MAPPING:
#
# data_management/models.py
#         ↓
# python manage.py makemigrations
#         ↓
# data_management/migrations/0001_initial.py
#         ↓
# python manage.py migrate
#         ↓
# Django ORM
#         ↓
# PostgreSQL / Neon
#         ↓
# Database tables
#
#
# DATABASE TABLES CREATED:
#
# DataSource
#     ↓
# data_management_datasource
#
# DataImport
#     ↓
# data_management_dataimport
#
#
# RELATIONSHIPS:
#
# User
#   ↓
# DataImport
#
# DataSource
#   ↓
# DataImport
#
#
# PROGRAMMING LANGUAGE CONCEPTS USED:
#
# - Imports
# - Classes
# - Class inheritance
# - Class attributes
# - Lists
# - Tuples
# - Dictionaries
# - Function calls
# - Keyword arguments
# - Object relationships
# - Foreign keys
# - Database constraints
# - Declarative programming
#
#
# IMPORTANT:
#
# This file describes database history.
#
# The database behaviour itself is normally changed in:
#
#     data_management/models.py
#
# After changing a model, Django creates another migration:
#
#     python manage.py makemigrations
#
# Existing migration logic should generally not be manually
# changed after it has already been applied.
#
# ============================================================


# ============================================================
# 1. IMPORTS
# ============================================================

import django.db.models.deletion  # Imports Django's database deletion behaviours such as CASCADE and PROTECT.
from django.conf import settings  # Imports the project's Django settings so this migration can reference the configured user model.
from django.db import migrations, models  # Imports Django's migration system and database model field definitions.


# ============================================================
# 2. MIGRATION CLASS
# ============================================================

class Migration(migrations.Migration):  # Defines this migration and inherits Django's Migration framework class.

    # ========================================================
    # 2.1 INITIAL MIGRATION FLAG
    # ========================================================

    initial = True  # Tells Django that this is the first migration for the data_management application.

    # ========================================================
    # 2.2 MIGRATION DEPENDENCIES
    # ========================================================

    dependencies = [  # Creates a list containing migrations that must exist before this migration can run.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Ensures the configured custom User model exists before DataImport creates its user relationship.
    ]  # Ends the migration dependency list.

    # ========================================================
    # 2.3 DATABASE OPERATIONS
    # ========================================================

    operations = [  # Creates the ordered list of database operations Django must perform.

        # ====================================================
        # 3. CREATE DATASOURCE MODEL
        # ====================================================
        #
        # PURPOSE:
        #
        # DataSource represents the external provider used
        # by MarketPulse to retrieve market information.
        #
        # In the current project this is primarily:
        #
        #     Alpaca
        #
        # Example:
        #
        # DataSource
        #     name = "Alpaca"
        #     url = "https://alpaca.markets/"
        #     api_key_required = True
        #     is_active = True
        #
        # ====================================================

        migrations.CreateModel(  # Tells Django to create a new database table from a model definition.
            name='DataSource',  # Sets the Django model name that this database operation creates.
            fields=[  # Starts the list of database columns belonging to DataSource.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Creates the automatically increasing primary-key ID.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Stores the date and time when the DataSource record is first created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Automatically updates the timestamp whenever the record is saved.
                ('name', models.CharField(max_length=100, unique=True)),  # Stores the provider name with a maximum of 100 characters and prevents duplicate names.
                ('url', models.URLField()),  # Stores the web address associated with the market-data provider.
                ('api_key_required', models.BooleanField(default=False)),  # Stores True or False to indicate whether the provider requires an API key.
                ('is_active', models.BooleanField(default=True)),  # Stores whether this provider is currently available for use.
            ],  # Ends the DataSource field list.
            options={  # Starts the dictionary containing additional Django model configuration.
                'abstract': False,  # Confirms that DataSource is a real database model rather than an abstract parent model.
            },  # Ends the DataSource model-options dictionary.
        ),  # Finishes the CreateModel operation for DataSource.

        # ====================================================
        # 4. CREATE DATAIMPORT MODEL
        # ====================================================
        #
        # PURPOSE:
        #
        # DataImport records a user's request to import
        # historical market data.
        #
        # Example workflow:
        #
        # User selects:
        #
        #     SPY
        #     01/09/2026
        #     07/10/2026
        #
        #         ↓
        #
        # DataImport record created
        #
        #         ↓
        #
        # Import process runs
        #
        #         ↓
        #
        # Historical observations are stored
        #
        #         ↓
        #
        # status = completed
        # records_imported = number of records
        #
        #
        # RELATIONSHIPS:
        #
        # User
        #   ↓
        # DataImport
        #
        # DataSource
        #   ↓
        # DataImport
        #
        # ====================================================

        migrations.CreateModel(  # Tells Django to create the DataImport database table.
            name='DataImport',  # Sets the Django model name created by this operation.
            fields=[  # Starts the list of database columns belonging to DataImport.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Creates the automatically increasing primary-key ID.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Records when the import job was originally created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Records the most recent time the import record was updated.
                ('symbol', models.CharField(max_length=20)),  # Stores the selected financial ticker such as SPY, AAPL or MSFT.
                ('start_date', models.DateField()),  # Stores the beginning date requested for the historical-data import.
                ('end_date', models.DateField()),  # Stores the final date requested for the historical-data import.
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),  # Stores the current import state using a controlled set of allowed values.
                ('records_imported', models.PositiveIntegerField(default=0)),  # Stores how many historical observations were successfully imported and prevents negative numbers.
                ('error_message', models.TextField(blank=True)),  # Stores an error description if an import fails and allows the field to remain empty.
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_imports', to=settings.AUTH_USER_MODEL)),  # Links the import to a user and deletes their import records if that user is deleted.
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_management.datasource')),  # Links the import to its DataSource and prevents that provider from being deleted while import records still reference it.
            ],  # Ends the DataImport field list.
            options={  # Starts additional configuration for the DataImport model.
                'abstract': False,  # Confirms that DataImport creates a real database table.
            },  # Ends the DataImport options dictionary.
        ),  # Finishes the CreateModel operation for DataImport.
    ]  # Ends the complete ordered migration operations list.


