# Generated by Django 5.2.17 on 2026-08-30 09:20

# ============================================================
# 1. IMPORT MIGRATION AND MODEL TOOLS
# ============================================================
import django.db.models.deletion  # Module import: I access Django's relationship-deletion behaviours.
from django.db import migrations, models  # Imports: I access migration operations and model-field definitions.

# ============================================================
# 2. DEFINE THE INITIAL MIGRATION
# ============================================================
class Migration(migrations.Migration):  # Class inheritance: I define this migration using Django's migration base class.
    initial = True  # Class attribute and Boolean: I mark this as an initial migration for the application.

    # --------------------------------------------------------
    # 2.1 REQUIRED CORE MIGRATION
    # --------------------------------------------------------
    dependencies = [  # List: I identify migrations that must be applied first.
        ('core', '0001_initial'),  # Tuple: I require the core application's initial migration.
    ]  # Closing bracket: I finish the dependency list.

    # --------------------------------------------------------
    # 2.2 DATABASE OPERATIONS
    # --------------------------------------------------------
    operations = [  # List: I collect the model-creation operations in their original order.

        # ====================================================
        # 3. CREATE THE BACKTEST TRADE MODEL
        # ====================================================
        migrations.CreateModel(  # Operation construction: I instruct Django to create the simulated-trade model and table.
            name='BacktestTrade',  # Keyword argument and string: I identify the model being created.
            fields=[  # List: I define pairs containing each field's name and configuration.

                # ------------------------------------------------
                # 3.1 PRIMARY KEY AND TIMESTAMPS
                # ------------------------------------------------
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Tuple and field: I define an automatic 64-bit primary key, excluded from Django's object serialization.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Timestamp field: Django sets the creation time when the object is first saved.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Timestamp field: Django refreshes this value when the field participates in a model save.

                # ------------------------------------------------
                # 3.2 SYMBOL AND TRADE DATES
                # ------------------------------------------------
                ('symbol', models.CharField(max_length=20)),  # Text field: I store an asset symbol with a 20-character limit.
                ('entry_date', models.DateField()),  # Date field: I store when the simulated position opened.
                ('exit_date', models.DateField(blank=True, null=True)),  # Optional date: blank permits empty validation input; null permits a database NULL.

                # ------------------------------------------------
                # 3.3 ENTRY AND EXIT PRICES
                # ------------------------------------------------
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=14)),  # Decimal field: I allow 14 total digits, including four decimal places.
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),  # Optional decimal: I use the same precision and allow a missing exit price.

                # ------------------------------------------------
                # 3.4 QUANTITIES AND PARTIAL-FILL STATUS
                # ------------------------------------------------
                ('requested_quantity', models.PositiveIntegerField(default=0)),  # Integer field: I store the requested units, allowing zero and defaulting to zero.
                ('quantity', models.PositiveIntegerField()),  # Integer field: I store the filled units; zero is allowed.
                ('partial_fill', models.BooleanField(default=False)),  # Boolean field: I record whether the requested quantity was only partly filled.

                # ------------------------------------------------
                # 3.5 COSTS AND PROFIT OR LOSS
                # ------------------------------------------------
                ('transaction_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),  # Decimal field: I store costs with two decimal places and a zero default.
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),  # Optional decimal: I store profit or loss when available.

                # ------------------------------------------------
                # 3.6 TRADE STATUS
                # ------------------------------------------------
                ('status', models.CharField(  # Tuple and field construction: I define the trade's status code.
                    choices=[  # List: I pair stored values with readable labels.
                        ('open', 'Open'),  # Tuple: I define the open-status value and label.
                        ('closed', 'Closed'),  # Tuple: I define the closed-status value and label.
                    ],  # Closing bracket: I finish the status choices.
                    default='open',  # Default argument: New model instances begin with open status.
                    max_length=20,  # Integer argument: I limit the status code to 20 characters.
                )),  # Closing delimiters: I finish the status field and its tuple.

                # ------------------------------------------------
                # 3.7 RELATIONSHIP TO THE PARENT BACKTEST
                # ------------------------------------------------
                ('backtest', models.ForeignKey(  # Relationship field: I link each trade to one parent backtest.
                    on_delete=django.db.models.deletion.CASCADE,  # Deletion behaviour: Django deletes related trades when their parent backtest is deleted.
                    related_name='trades',  # Reverse relationship: Application code can retrieve records with backtest.trades.all().
                    to='core.backtest',  # String model reference: I identify Backtest in the core application.
                )),  # Closing delimiters: I finish the foreign key and its tuple.
            ],  # Closing bracket: I finish the BacktestTrade field list.
            options={  # Dictionary: I record model configuration.
                'abstract': False,  # Boolean option: This is a concrete model with its own database table.
            },  # Closing brace: I finish the model options.
        ),  # Closing call: I finish the BacktestTrade creation operation.

        # ====================================================
        # 4. CREATE THE STRATEGY RULE MODEL
        # ====================================================
        migrations.CreateModel(  # Operation construction: I instruct Django to create the strategy-rule model and table.
            name='StrategyRule',  # Keyword argument and string: I identify the model being created.
            fields=[  # List: I define the rule model's field-name and field-instance pairs.

                # ------------------------------------------------
                # 4.1 PRIMARY KEY AND TIMESTAMPS
                # ------------------------------------------------
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Field: I define an automatic 64-bit primary key with the readable label ID.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Timestamp field: I record the object's creation time.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Timestamp field: I record updates when this field participates in a model save.

                # ------------------------------------------------
                # 4.2 RULE NAME AND SYMBOL
                # ------------------------------------------------
                ('name', models.CharField(max_length=160)),  # Text field: I store a readable rule name with a 160-character limit.
                ('symbol', models.CharField(max_length=20)),  # Text field: I store the asset symbol used by the rule.

                # ------------------------------------------------
                # 4.3 MOVING-AVERAGE CONDITION CHOICES
                # ------------------------------------------------
                ('condition_type', models.CharField(  # Tuple and field: I define the rule's condition code.
                    choices=[  # List: I define the supported condition values and labels.
                        ('ma_cross_up', 'Fast MA crosses above Slow MA'),  # Tuple: I describe an upward moving-average crossover.
                        ('ma_cross_down', 'Fast MA crosses below Slow MA'),  # Tuple: I describe a downward moving-average crossover.
                    ],  # Closing bracket: I finish the condition choices.
                    max_length=30,  # Integer argument: I limit the stored condition code to 30 characters.
                )),  # Closing delimiters: I finish the condition field and its tuple.

                # ------------------------------------------------
                # 4.4 ACTION CHOICES
                # ------------------------------------------------
                ('action', models.CharField(  # Tuple and field: I define the rule's action code.
                    choices=[  # List: I define the available action values and labels.
                        ('buy', 'Buy'),  # Tuple: I define the buy action.
                        ('sell', 'Sell'),  # Tuple: I define the sell action.
                    ],  # Closing bracket: I finish the action choices.
                    max_length=10,  # Integer argument: I limit the stored action code to 10 characters.
                )),  # Closing delimiters: I finish the action field and its tuple.

                # ------------------------------------------------
                # 4.5 PARAMETERS AND ACTIVE STATUS
                # ------------------------------------------------
                ('parameters', models.JSONField(default=dict)),  # JSON field and callable default: I store rule settings and create a fresh dictionary for each new instance.
                ('is_active', models.BooleanField(default=True)),  # Boolean field: New rule instances begin active.

                # ------------------------------------------------
                # 4.6 RELATIONSHIP TO THE PARENT STRATEGY
                # ------------------------------------------------
                ('strategy', models.ForeignKey(  # Relationship field: I link each rule to one parent strategy.
                    on_delete=django.db.models.deletion.CASCADE,  # Deletion behaviour: Django deletes related rules when their parent strategy is deleted.
                    related_name='rules',  # Reverse relationship: Application code can use strategy.rules.all().
                    to='core.strategy',  # String model reference: I identify Strategy in the core application.
                )),  # Closing delimiters: I finish the foreign key and its tuple.
            ],  # Closing bracket: I finish the StrategyRule field list.
            options={  # Dictionary: I record model configuration.
                'abstract': False,  # Boolean option: This model has its own database table.
            },  # Closing brace: I finish the model options.
        ),  # Closing call: I finish the StrategyRule creation operation.
    ]  # Closing bracket: I finish the migration's operation list.