# Generated by Django 5.2.17 on 2026-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('stochastic', '1. Stochastic Models'), ('time_series', '2. Time-Series Models'), ('machine_learning', '3. Machine Learning Models'), ('factor', '4. Factor Models'), ('portfolio', '5. Portfolio Optimisation'), ('derivatives', '6. Derivatives Pricing'), ('monte_carlo', '7. Simulation & Monte Carlo')], max_length=40)),
                ('description', models.TextField()),
                ('purpose', models.TextField(blank=True)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('data_requirements', models.JSONField(blank=True, default=list)),
                ('output_type', models.CharField(blank=True, max_length=250)),
                ('implementation_status', models.CharField(choices=[('catalogued', 'Catalogued'), ('ready', 'Ready to Run'), ('experimental', 'Experimental')], default='catalogued', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Strategy Library Item',
                'verbose_name_plural': 'Strategy Library Items',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
    ]
