# Generated by Django 5.2.17 on 2026-08-30 19:20

# ============================================================
# 1. IMPORT MIGRATION AND FIELD TOOLS
# ============================================================
from django.db import migrations, models  # Import: I access Django's migration operations and model-field definitions.

# ============================================================
# 2. DEFINE THE MIGRATION CLASS
# ============================================================
class Migration(migrations.Migration):  # Class inheritance: I define this migration using Django's migration base class.

    # --------------------------------------------------------
    # 2.1 REQUIRED PREVIOUS MIGRATION
    # --------------------------------------------------------
    dependencies = [  # Class attribute and list: I identify migrations that must be applied first.
        ('strategy_builder', '0001_initial'),  # Tuple: I name the application and its required previous migration.
    ]  # Closing bracket: I finish the dependency list.

    # --------------------------------------------------------
    # 2.2 DATABASE OPERATIONS
    # --------------------------------------------------------
    operations = [  # Class attribute and list: I collect the operations performed by this migration.
        migrations.CreateModel(  # Operation construction: I tell Django to create the model and its database table.
            name='StrategyLibraryItem',  # Keyword argument and string: I identify the model being created.
            fields=[  # List: I define the model's field-name and field-instance pairs.

                # ------------------------------------------------
                # 3. PRIMARY KEY AND TIMESTAMPS
                # ------------------------------------------------
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Tuple and field: I define an automatic 64-bit primary key; serialize=False excludes this field from Django's object serialization.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # Timestamp field: Django sets the creation time when an object is first saved.
                ('updated_at', models.DateTimeField(auto_now=True)),  # Timestamp field: Django updates this value when the field participates in a model save.

                # ------------------------------------------------
                # 4. IDENTIFIER AND DISPLAY NAME
                # ------------------------------------------------
                ('code', models.SlugField(max_length=100, unique=True)),  # Slug field: I define a unique internal code with a 100-character limit.
                ('name', models.CharField(max_length=150)),  # Text field: I define a readable name with a 150-character limit.

                # ------------------------------------------------
                # 5. MODEL CATEGORY CHOICES
                # ------------------------------------------------
                ('category', models.CharField(  # Tuple and field construction: I define the category code.
                    choices=[  # List: I pair stored category codes with readable labels.
                        ('stochastic', '1. Stochastic Models'),  # Tuple: I define the stochastic category's value and label.
                        ('time_series', '2. Time-Series Models'),  # Tuple: I define the time-series category.
                        ('machine_learning', '3. Machine Learning Models'),  # Tuple: I define the machine-learning category.
                        ('factor', '4. Factor Models'),  # Tuple: I define the factor-model category.
                        ('portfolio', '5. Portfolio Optimisation'),  # Tuple: I define the portfolio category.
                        ('derivatives', '6. Derivatives Pricing'),  # Tuple: I define the derivatives category.
                        ('monte_carlo', '7. Simulation & Monte Carlo'),  # Tuple: I define the simulation category.
                    ],  # Closing bracket: I finish the category choices.
                    max_length=40,  # Integer argument: I limit the stored category code to 40 characters.
                )),  # Closing delimiters: I finish the category field and its tuple.

                # ------------------------------------------------
                # 6. MODEL DESCRIPTIONS AND JSON SETTINGS
                # ------------------------------------------------
                ('description', models.TextField()),  # Text field: I store the model's explanation.
                ('purpose', models.TextField(blank=True)),  # Validation option: I allow the purpose text to be empty.
                ('default_parameters', models.JSONField(blank=True, default=dict)),  # JSON field and callable default: I allow empty parameters and create a fresh dictionary for each new instance.
                ('data_requirements', models.JSONField(blank=True, default=list)),  # JSON field and callable default: I allow empty requirements and create a fresh list for each new instance.
                ('output_type', models.CharField(blank=True, max_length=250)),  # Text field: I allow an optional output description of up to 250 characters.

                # ------------------------------------------------
                # 7. IMPLEMENTATION STATUS CHOICES
                # ------------------------------------------------
                ('implementation_status', models.CharField(  # Tuple and field: I define the stored implementation-status code.
                    choices=[  # List: I define status values and readable labels.
                        ('catalogued', 'Catalogued'),  # Tuple: I identify an entry recorded in the catalogue.
                        ('ready', 'Ready to Run'),  # Tuple: I define the ready-status label.
                        ('experimental', 'Experimental'),  # Tuple: I define the experimental-status label.
                    ],  # Closing bracket: I finish the status choices.
                    default='catalogued',  # Default argument: New model instances begin with catalogued status.
                    max_length=20,  # Integer argument: I limit the stored status code to 20 characters.
                )),  # Closing delimiters: I finish the status field and its tuple.

                # ------------------------------------------------
                # 8. ACTIVE STATUS AND DISPLAY ORDER
                # ------------------------------------------------
                ('is_active', models.BooleanField(default=True)),  # Boolean field: New instances begin active.
                ('display_order', models.PositiveIntegerField(default=0)),  # Integer field: I store a non-negative display-order value, defaulting to zero.
            ],  # Closing bracket: I finish the field definitions.

            # ----------------------------------------------------
            # 9. MODEL METADATA
            # ----------------------------------------------------
            options={  # Dictionary: I record the model's descriptive names and default ordering.
                'verbose_name': 'Strategy Library Item',  # Key-value pair: I define the readable singular model name.
                'verbose_name_plural': 'Strategy Library Items',  # Key-value pair: I define the readable plural name.
                'ordering': ['category', 'display_order', 'name'],  # List: I sort default queries by category code, display order, then name.
            },  # Closing brace: I finish the model options.
        ),  # Closing call: I finish the CreateModel operation.
    ]  # Closing bracket: I finish the migration's operation list.