# Generated by Django 5.2.17 on 2026-09-12 16:22

# ============================================================
# COMMUNITY - INITIAL DATABASE MIGRATION
# ============================================================
# FILE PURPOSE:
# This file creates the first database structure for the
# MarketPulse community application.
#
# It creates:
# 1. CommunityPost
# 2. PrivateMessage
#
# DJANGO FRAMEWORK FLOW:
#
# community/models.py
#        ↓
# python manage.py makemigrations
#        ↓
# community/migrations/0001_initial.py
#        ↓
# python manage.py migrate
#        ↓
# Django Migration Framework
#        ↓
# Database SchemaEditor
#        ↓
# PostgreSQL / Database tables
#
# USER RELATIONSHIP FLOW:
#
# settings.AUTH_USER_MODEL
#        ↓
# CommunityPost.author
#        ↓
# User creates community posts
#
# settings.AUTH_USER_MODEL
#        ↓
# PrivateMessage.sender
# PrivateMessage.recipient
#        ↓
# Users send private messages to each other
#
# PROGRAMMING LANGUAGE CONCEPTS USED:
#
# - Imports / modules
# - Classes
# - Inheritance
# - Variables / class attributes
# - Boolean values
# - Lists
# - Tuples
# - Dictionaries
# - Strings
# - Objects
# - Function and class calls
# - Keyword arguments
# - Object-oriented programming
# - Database relationships / Foreign Keys
# ============================================================

# ============================================================
# 1. IMPORTS
# ============================================================
import django.db.models.deletion  # Imports Django's database deletion behaviour, including CASCADE.
from django.conf import settings  # Imports the project settings so this migration can use the configured user model.
from django.db import migrations, models  # Imports Django migration tools and database model field classes.

# ============================================================
# 2. MIGRATION CLASS
# ============================================================
class Migration(migrations.Migration):  # Defines a class called Migration and inherits Django's Migration behaviour.
    initial = True  # Boolean class attribute telling Django this is an initial migration for the community app.

    # ========================================================
    # 3. MIGRATION DEPENDENCIES
    # ========================================================
    dependencies = [  # A list containing migrations/models that must exist before this migration can run.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # Makes this migration depend on the project's configured Django user model.
    ]  # Ends the dependencies list.

    # ========================================================
    # 4. DATABASE OPERATIONS
    # ========================================================
    operations = [  # A list of database schema operations Django must perform.

        # ====================================================
        # 4.1 CREATE COMMUNITYPOST MODEL
        # ====================================================
        migrations.CreateModel(  # Calls Django's CreateModel operation to create a new database table/model.
            name='CommunityPost',  # Keyword argument giving the new Django model the name CommunityPost.
            fields=[  # A list of tuples describing every database field belonging to CommunityPost.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Tuple defining the automatic unique primary-key ID for each post.
                ('post_type', models.CharField(choices=[('UPDATE', 'Market Update'), ('WARNING', 'Trading Warning'), ('IDEA', 'Trading Idea'), ('RISK', 'Risk Alert'), ('DISCUSSION', 'Discussion')], default='UPDATE', max_length=20)),  # CharField storing the post category and limiting it to predefined choices.
                ('ticker', models.CharField(blank=True, help_text='Optional stock or asset ticker, for example AAPL or MSFT.', max_length=15)),  # CharField storing an optional market ticker such as AAPL or MSFT.
                ('content', models.TextField(max_length=1500)),  # TextField storing the main community-post text with a maximum length of 1500 characters.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # DateTimeField automatically recording when the post is first created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # DateTimeField automatically updating whenever the post is changed.
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),  # ForeignKey linking each post to its author and deleting the posts if that user is deleted.
            ],  # Ends the CommunityPost fields list.
            options={  # Dictionary containing extra configuration for the CommunityPost model.
                'ordering': ['-created_at'],  # List telling Django to return newest community posts first by default.
            },  # Ends the CommunityPost options dictionary.
        ),  # Ends the CreateModel operation for CommunityPost.

        # ====================================================
        # 4.2 CREATE PRIVATEMESSAGE MODEL
        # ====================================================
        migrations.CreateModel(  # Calls Django's CreateModel operation to create the PrivateMessage database table/model.
            name='PrivateMessage',  # Keyword argument giving the new Django model the name PrivateMessage.
            fields=[  # A list of tuples describing every database field belonging to PrivateMessage.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Tuple defining the automatic unique primary-key ID for each private message.
                ('subject', models.CharField(max_length=150)),  # CharField storing the private-message subject with a maximum length of 150 characters.
                ('body', models.TextField(max_length=3000)),  # TextField storing the main private-message content with a maximum length of 3000 characters.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # DateTimeField automatically recording when the private message is created.
                ('is_read', models.BooleanField(default=False)),  # BooleanField storing True or False to track whether the recipient has read the message.
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_marketpulse_messages', to=settings.AUTH_USER_MODEL)),  # ForeignKey connecting the message to the user who receives it.
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_marketpulse_messages', to=settings.AUTH_USER_MODEL)),  # ForeignKey connecting the message to the user who sends it.
            ],  # Ends the PrivateMessage fields list.
            options={  # Dictionary containing extra configuration for the PrivateMessage model.
                'ordering': ['-created_at'],  # List telling Django to return newest private messages first by default.
            },  # Ends the PrivateMessage options dictionary.
        ),  # Ends the CreateModel operation for PrivateMessage.
    ]  # Ends the list of migration operations.