# Generated by Django 5.2.17 on 2026-10-07 20:24
# ============================================================
# COMMUNITY - CONVERSATION DATABASE MIGRATION
# ============================================================
# FILE PURPOSE:
# This migration changes the database structure for the
# community application.
#
# It:
# 1. Creates the Conversation model.
# 2. Connects users to conversations.
# 3. Connects PrivateMessage records to conversations.
# 4. Adds database indexes for faster message searches.
#
# DJANGO FRAMEWORK FLOW:
#
# community/models.py
#       ↓
# python manage.py makemigrations
#       ↓
# This migration file
#       ↓
# python manage.py migrate
#       ↓
# Django migration framework / SchemaEditor
#       ↓
# Database tables, relationships and indexes
#
# PROGRAMMING LANGUAGE CONCEPTS USED:
#
# Imports
# Classes
# Inheritance
# Class attributes
# Lists
# Tuples
# Dictionaries
# Objects
# Function / constructor calls
# Positional arguments
# Keyword arguments
# Boolean values
# Strings
# Database relationships
# Dependencies
# ============================================================

# ============================================================
# 1. IMPORTS
# Programming concept: modules and imports
# ============================================================
import django.db.models.deletion  # IMPORT: gives this file access to Django's database deletion behaviours such as CASCADE.
from django.conf import settings  # FROM IMPORT: imports the Django project settings object so this migration can use AUTH_USER_MODEL.
from django.db import migrations, models  # MULTIPLE IMPORT: imports Django migration tools and database model field classes.

# ============================================================
# 2. MIGRATION CLASS
# Programming concepts: class, inheritance and OOP
# ============================================================
class Migration(migrations.Migration):  # CLASS + INHERITANCE: creates Migration as a child of Django's migrations.Migration class.

    # ========================================================
    # 3. MIGRATION DEPENDENCIES
    # Programming concepts: class attribute, list and tuple
    # ========================================================
    dependencies = [  # LIST: stores the migrations that must already exist before this migration can run.
        ('community', '0001_initial'),  # TUPLE: says community migration 0001_initial must run before this migration.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # FUNCTION CALL: adds a dependency on the project's configured User model.
    ]  # LIST END: finishes the dependencies list.

    # ========================================================
    # 4. DATABASE OPERATIONS
    # Programming concepts: list, objects and function calls
    # ========================================================
    operations = [  # LIST: contains all database changes Django must perform in this migration.

        # ====================================================
        # 4.1 CREATE THE CONVERSATION MODEL
        # Programming concepts:
        # object construction, keyword arguments, lists,
        # tuples, fields and relationships
        # ====================================================
        migrations.CreateModel(  # OBJECT/FUNCTION CALL: tells Django to create a new database model/table.
            name='Conversation',  # KEYWORD ARGUMENT + STRING: gives the new model the name Conversation.
            fields=[  # LIST: contains all fields belonging to the Conversation model.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # TUPLE + OBJECT: creates the automatic numeric primary key for each Conversation.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # TUPLE + DATETIME FIELD: automatically stores when the conversation is first created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # TUPLE + DATETIME FIELD: automatically updates the timestamp whenever the conversation changes.
                ('participants', models.ManyToManyField(related_name='marketpulse_conversations', to=settings.AUTH_USER_MODEL)),  # MANY-TO-MANY RELATIONSHIP: allows one conversation to contain many users and one user to belong to many conversations.
            ],  # LIST END: finishes the Conversation fields list.
            options={  # DICTIONARY: stores extra configuration for the Conversation model.
                'ordering': ['-updated_at'],  # KEY/VALUE PAIR + LIST: orders conversations by newest updated_at value first.
            },  # DICTIONARY END: finishes the Conversation model options.
        ),  # OPERATION END: finishes the CreateModel database operation.

        # ====================================================
        # 4.2 ADD CONVERSATION TO PRIVATE MESSAGE
        # Programming concepts:
        # object construction, keyword arguments,
        # relationship and Boolean values
        # ====================================================
        migrations.AddField(  # FUNCTION/OBJECT CALL: tells Django to add another field to an existing model.
            model_name='privatemessage',  # KEYWORD ARGUMENT + STRING: identifies PrivateMessage as the model being changed.
            name='conversation',  # KEYWORD ARGUMENT + STRING: names the new field conversation.
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.conversation'),  # FOREIGN KEY: connects each PrivateMessage to a Conversation and deletes its messages if that Conversation is deleted.
        ),  # OPERATION END: finishes the AddField database operation.

        # ====================================================
        # 4.3 ADD CONVERSATION + CREATED_AT INDEX
        # Programming concepts:
        # object construction, list and keyword arguments
        # ====================================================
        migrations.AddIndex(  # FUNCTION/OBJECT CALL: tells Django to create a database index.
            model_name='privatemessage',  # KEYWORD ARGUMENT: says the index belongs to the PrivateMessage model.
            index=models.Index(fields=['conversation', 'created_at'], name='community_conv_date_idx'),  # INDEX OBJECT: indexes conversation and created_at together for conversation/time based lookups.
        ),  # OPERATION END: finishes the first AddIndex operation.

        # ====================================================
        # 4.4 ADD RECIPIENT + IS_READ INDEX
        # Programming concepts:
        # object construction, list and keyword arguments
        # ====================================================
        migrations.AddIndex(  # FUNCTION/OBJECT CALL: tells Django to create another database index.
            model_name='privatemessage',  # KEYWORD ARGUMENT: says this index also belongs to PrivateMessage.
            index=models.Index(fields=['recipient', 'is_read'], name='community_unread_idx'),  # INDEX OBJECT: indexes recipient and is_read together for unread-message lookups.
        ),  # OPERATION END: finishes the second AddIndex operation.
    ]  # LIST END: finishes all database operations for this migration.