# ============================================================
# ACCOUNT APP - INITIAL DATABASE MIGRATION
# ============================================================
# File purpose:
# This Django migration creates the first database structure
# for the accounts application.
#
# FRAMEWORK FLOW:
#
# accounts/models.py
#       ↓
# Django Model classes
#       ↓
# python manage.py makemigrations
#       ↓
# accounts/migrations/0001_initial.py
#       ↓
# python manage.py migrate
#       ↓
# Django ORM
#       ↓
# PostgreSQL / Database
#       ↓
# User table + UserProfile table
#
# PROGRAMMING LANGUAGE CONCEPTS USED:
#
# Imports / Modules
# Classes
# Inheritance
# Class attributes
# Variables
# Lists
# Tuples
# Dictionaries
# Strings
# Integers
# Booleans
# None
# Function / constructor calls
# Positional arguments
# Keyword arguments
# Objects
# Nested data structures
# Relationships between objects
#
# DJANGO FRAMEWORK CONCEPTS USED:
#
# Migrations
# Models
# ORM
# Authentication
# Database fields
# Primary keys
# Many-to-many relationships
# One-to-one relationships
# Foreign relationships
# Model managers
# Validators
# Migration dependencies
# ============================================================

# ============================================================
# 1. DJANGO GENERATED MIGRATION INFORMATION
# ============================================================

# Generated by Django 5.2.17 on 2026-08-30 09:20  # Comment: Django automatically created this migration file and recorded its version and creation date.

# ============================================================
# 2. IMPORTS / MODULES
# ============================================================

import django.contrib.auth.models  # Import: gives this migration access to Django authentication model tools such as UserManager.
import django.contrib.auth.validators  # Import: gives access to Django authentication validation tools such as UnicodeUsernameValidator.
import django.db.models.deletion  # Import: provides database relationship deletion behaviours such as CASCADE.
import django.utils.timezone  # Import: provides Django timezone-aware date and time functions.
from django.conf import settings  # Import: gets values from the Django project settings, including the configured custom user model.
from django.db import migrations, models  # Import: migrations provides migration operations and models provides database field classes.

# ============================================================
# 3. MIGRATION CLASS
# ============================================================

class Migration(migrations.Migration):  # Class + inheritance: creates this migration by inheriting Django's base Migration class.
    # --------------------------------------------------------
    # 3.1 INITIAL MIGRATION SETTING
    # --------------------------------------------------------

    initial = True  # Boolean + class attribute: tells Django that this is the first migration for the accounts application.

    # --------------------------------------------------------
    # 3.2 MIGRATION DEPENDENCIES
    # --------------------------------------------------------

    dependencies = [  # List: stores migrations that must already exist before Django runs this migration.
        ('auth', '0012_alter_user_first_name_max_length'),  # Tuple: says this migration depends on migration 0012 from Django's auth application.
    ]  # List ending: finishes the migration dependency collection.

    # --------------------------------------------------------
    # 3.3 MIGRATION OPERATIONS
    # --------------------------------------------------------

    operations = [  # List: contains the database operations Django must perform for this migration.

        # ====================================================
        # 4. CREATE CUSTOM USER MODEL
        # ====================================================

        migrations.CreateModel(  # Function/class call: tells Django to create a new database model and table.
            name='User',  # Keyword argument + string: gives the new model the Python name User.
            fields=[  # List: contains all database fields belonging to the User model.

                # ------------------------------------------------
                # 4.1 USER PRIMARY KEY
                # ------------------------------------------------

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Tuple + object creation: creates an automatically increasing primary-key ID field.

                # ------------------------------------------------
                # 4.2 DJANGO AUTHENTICATION FIELDS
                # ------------------------------------------------

                ('password', models.CharField(max_length=128, verbose_name='password')),  # Tuple + CharField: stores the user's hashed password with a maximum length of 128 characters.
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),  # DateTimeField: stores when the user last logged in and allows an empty database value.
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),  # BooleanField: records whether the user has all Django permissions.

                # ------------------------------------------------
                # 4.3 USERNAME
                # ------------------------------------------------

                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),  # CharField + dictionary + list: stores a unique username and validates its allowed characters.

                # ------------------------------------------------
                # 4.4 PERSONAL INFORMATION
                # ------------------------------------------------

                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),  # CharField: stores an optional first name up to 150 characters.
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),  # CharField: stores an optional last name up to 150 characters.
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),  # EmailField: stores an optional email address and applies email-format validation.

                # ------------------------------------------------
                # 4.5 ACCOUNT STATUS AND ACCESS
                # ------------------------------------------------

                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),  # BooleanField: controls whether the user can access the Django administration site.
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),  # BooleanField: controls whether Django treats the account as active.
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),  # DateTimeField + callable: stores when the user joined using Django's current timezone-aware time.

                # ------------------------------------------------
                # 4.6 MARKETPULSE CUSTOM USER FIELDS
                # ------------------------------------------------

                ('role', models.CharField(choices=[('trader', 'Trader'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], default='trader', max_length=20)),  # CharField + list of tuples: limits the MarketPulse user role to Trader, Reviewer, or Admin.
                ('email_verified', models.BooleanField(default=False)),  # BooleanField: records whether the user's email address has been verified.

                # ------------------------------------------------
                # 4.7 DJANGO GROUP RELATIONSHIP
                # ------------------------------------------------

                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),  # ManyToManyField: allows one user to belong to many authentication groups and each group to contain many users.

                # ------------------------------------------------
                # 4.8 DJANGO PERMISSION RELATIONSHIP
                # ------------------------------------------------

                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),  # ManyToManyField: allows many individual permissions to be assigned directly to a user.
            ],  # List ending: finishes the collection of User database fields.

            # ------------------------------------------------
            # 4.9 USER MODEL METADATA
            # ------------------------------------------------

            options={  # Dictionary: stores configuration information about the User model.
                'verbose_name': 'user',  # Dictionary key/value: specifies the human-readable singular name of the model.
                'verbose_name_plural': 'users',  # Dictionary key/value: specifies the human-readable plural name of the model.
                'abstract': False,  # Boolean: confirms that User is a real database model instead of an abstract model.
            },  # Dictionary ending: finishes the User model metadata.

            # ------------------------------------------------
            # 4.10 USER MODEL MANAGER
            # ------------------------------------------------

            managers=[  # List: contains the managers Django attaches to the User model.
                ('objects', django.contrib.auth.models.UserManager()),  # Tuple + object creation: attaches Django's UserManager as User.objects for user-related database operations.
            ],  # List ending: finishes the manager configuration.
        ),  # CreateModel ending: completes the operation that creates the User model.

        # ====================================================
        # 5. CREATE USER PROFILE MODEL
        # ====================================================

        migrations.CreateModel(  # Function/class call: tells Django to create another model and database table.
            name='UserProfile',  # Keyword argument + string: gives the second model the name UserProfile.
            fields=[  # List: contains all database fields belonging to UserProfile.

                # ------------------------------------------------
                # 5.1 PROFILE PRIMARY KEY
                # ------------------------------------------------

                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # BigAutoField: creates the automatically increasing primary-key ID for each profile.

                # ------------------------------------------------
                # 5.2 PROFILE INFORMATION
                # ------------------------------------------------

                ('bio', models.TextField(blank=True, max_length=500)),  # TextField: stores an optional biography with a maximum length of 500 characters.
                ('location', models.CharField(blank=True, max_length=80)),  # CharField: stores an optional user location up to 80 characters.

                # ------------------------------------------------
                # 5.3 TRADING EXPERIENCE
                # ------------------------------------------------

                ('trading_experience', models.PositiveIntegerField(default=0)),  # PositiveIntegerField: stores trading experience as a non-negative whole number.

                # ------------------------------------------------
                # 5.4 RISK MANAGEMENT SETTINGS
                # ------------------------------------------------

                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),  # CharField + choices: limits risk tolerance to Conservative, Moderate, or Aggressive.
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=100, max_digits=12)),  # DecimalField: stores the user's maximum daily loss accurately using up to 12 digits and 2 decimal places.

                # ------------------------------------------------
                # 5.5 PREFERRED MARKET
                # ------------------------------------------------

                ('preferred_markets', models.CharField(choices=[('stocks', 'Stocks'), ('etfs', 'ETFs'), ('crypto', 'Cryptocurrency'), ('forex', 'Forex')], default='stocks', max_length=20)),  # CharField + choices: stores the user's selected preferred financial market.

                # ------------------------------------------------
                # 5.6 AUTOMATIC TIMESTAMPS
                # ------------------------------------------------

                ('created_at', models.DateTimeField(auto_now_add=True)),  # DateTimeField: automatically records the date and time when the profile is first created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # DateTimeField: automatically updates the timestamp whenever the profile is saved.

                # ------------------------------------------------
                # 5.7 USER ↔ USERPROFILE RELATIONSHIP
                # ------------------------------------------------

                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),  # OneToOneField: connects exactly one UserProfile to one User; CASCADE deletes the profile when its user is deleted.
            ],  # List ending: finishes the collection of UserProfile database fields.
        ),  # CreateModel ending: completes the operation that creates the UserProfile model.
    ]  # List ending: finishes all database operations contained in this migration.