"""
============================================================
MARKETPULSE - CORE HOME / DASHBOARD VIEWS
============================================================

SHORT PURPOSE:

This file controls the main MarketPulse Home page, Dashboard,
generated Alerts and configurable Alert Rules.

It receives browser requests, gets information from Django
models through the ORM, prepares template context dictionaries
and returns rendered HTML pages or redirects.

============================================================
FRAMEWORK MAPPING
============================================================

Browser
    ↓
marketpulse/urls.py
    ↓
core/views.py
    ↓
Django Forms / Django ORM
    ↓
PostgreSQL / Neon
    ↓
Template Context
    ↓
templates/home.html
templates/dashboard.html

============================================================
DJANGO MVC / MVT IDEA
============================================================

MarketPulse follows Django's MVT architecture:

MODEL
    ↓
core/models.py
community/models.py
analysis_tools/models.py

VIEW
    ↓
core/views.py

TEMPLATE
    ↓
templates/home.html
templates/dashboard.html

Django calls this Model-View-Template rather than the more
general Model-View-Controller terminology.

============================================================
HOME PAGE PURPOSE
============================================================

The MarketPulse Home page introduces the current version of
the platform and provides a concise overview of the features
available to the user.

The Home page is divided into several areas:

1. MarketPulse hero / introduction
2. Current technology stack
3. Main application feature summary
4. Latest Community activity
5. Private Inbox preview
6. Compact About MarketPulse section
7. Educational-use notice

The Home page now represents the actual application rather
than the original MarketPulse project proposal.

MarketPulse currently focuses on:

    Research Markets
        ↓
    Market Data
        ↓
    Test Strategies
        ↓
    Backtesting / Robustness
        ↓
    Manage Trading Risk
        ↓
    Position Sizing / Stop-Loss / Reward-to-Risk
        ↓
    Monitor Conditions
        ↓
    Dashboard / Alerts
        ↓
    Communicate
        ↓
    Community / Inbox

============================================================
HOME PAGE FEATURE ARCHITECTURE
============================================================

The explanatory information displayed by home.html is defined
in this file using configuration constants.

core/views.py
    ↓
Defines application content
    ↓
home()
    ↓
Template context
    ↓
templates/home.html

Instead of writing all feature explanations directly inside
the HTML template, the view can supply structured information
such as:

    HOME_TECHNOLOGY_STACK
    HOME_CORE_FEATURES
    HOME_FEATURE_GUIDE

============================================================
COMMUNITY ARCHITECTURE
============================================================

CommunityPost
    ↓
Stores public MarketPulse posts
    ↓
core.views.home
    ↓
recent_posts
    ↓
templates/home.html
    ↓
Community Pulse Preview

The complete Community workflow remains in:

    community/views.py

============================================================
PRIVATE MESSAGING ARCHITECTURE
============================================================

PrivateMessage
    ↓
Stores private communication
    ↓
core.views.home
    ↓
recent_messages
    ↓
unread_messages
    ↓
templates/home.html

The complete Inbox workflow remains in:

    community/views.py

============================================================
DASHBOARD PURPOSE
============================================================

The Dashboard is the authenticated user's main MarketPulse
control centre.

It summarises:

1. User strategies
2. Backtest activity
3. Average strategy win rate
4. Historical market-data storage
5. Selected market benchmark
6. Stored historical chart data
7. Latest Market Condition
8. Persistent generated alerts
9. Configurable alert rules
10. Unread alert count
11. Recent backtest activity

============================================================
ALERT ARCHITECTURE
============================================================

AlertRule
    ↓
Defines what MarketPulse should monitor

Example:

    SPY
    Price
    Greater Than
    800

Alert
    ↓
Represents an actual notification generated by MarketPulse

Example:

    "SPY moved above $800"

============================================================
LIVE MARKET DATA
============================================================

Django-rendered Dashboard
    ↓
templates/dashboard.html
    ↓
JavaScript
    ↓
/api/dashboard/market-overview/
    ↓
MarketPulse API
    ↓
Alpaca service
    ↓
Alpaca

The normal Django Dashboard view supplies PostgreSQL and user
information immediately, while JavaScript can later retrieve
current market information asynchronously.

============================================================
PROGRAMMING CONCEPTS USED IN THIS FILE
============================================================

This file demonstrates:

- imports
- constants
- lists
- dictionaries
- functions
- function parameters
- decorators
- conditional statements
- loops
- list comprehensions
- QuerySets
- method chaining
- object relationships
- aggregation
- authentication
- authorization
- HTTP POST restrictions
- form validation
- database CRUD operations
- template context
- redirects
- exception-safe object retrieval

============================================================
"""


# ============================================================
# 1. DJANGO IMPORTS
# ============================================================

from django.contrib import messages  # Django feature: sends one-time success/error/info messages to the next rendered page.
from django.contrib.auth.decorators import login_required  # Decorator concept: protects a view so only authenticated users can access it.
from django.db.models import Avg  # ORM aggregation concept: calculates an average directly in the database.
from django.shortcuts import (  # Import group: useful Django shortcut functions are imported together.
    get_object_or_404,  # Django shortcut: gets one database object or automatically returns HTTP 404 when it does not exist.
    redirect,  # Django shortcut: sends the browser to another URL.
    render,  # Django shortcut: combines a template with context data and returns an HTTP response.
)
from django.utils import timezone  # Django utility: provides timezone-aware date and time handling.
from django.views.decorators.http import require_POST  # Decorator concept: restricts a view so it accepts POST requests only.


# ============================================================
# 2. INTERNAL ANALYTICS MODEL
# ============================================================

# analysis_tools remains the internal analytical layer.
# Market Condition results are shown on the Dashboard and
# Data workflow rather than as a separate public application.

from analysis_tools.models import (  # Cross-app import: core can use a model belonging to analysis_tools.
    MarketRegime,  # Django model class: represents a saved Market Condition / regime analysis.
)


# ============================================================
# 3. CORE MODELS
# ============================================================

from .models import (  # Relative import concept: the dot means import from the current Django application.
    Alert,  # Django model: stores generated user notifications.
    AlertRule,  # Django model: stores rules defining what MarketPulse should monitor.
    Backtest,  # Django model: stores historical strategy-test results.
    MarketData,  # Django model: stores historical OHLCV market observations.
    Strategy,  # Django model: stores user trading strategies.
)


# ============================================================
# 4. CORE FORMS
# ============================================================

from .forms import (  # Relative import: imports forms from core/forms.py.
    AlertEditForm,  # Django ModelForm: validates edits to an existing generated Alert.
    AlertRuleForm,  # Django ModelForm: validates creation and editing of AlertRule objects.
)


# ============================================================
# 5. COMMUNITY MODELS
# ============================================================

from community.models import (  # Cross-application import: the Home page needs Community information.
    CommunityPost,  # Django model: stores public Community posts.
    PrivateMessage,  # Django model: stores private user-to-user messages.
)


# ============================================================
# 6. HOME PAGE CONFIGURATION
# ============================================================
# Programming concept:
#
# These uppercase variables are constants by convention.
# Python does not make them truly immutable, but uppercase
# names tell another programmer that they are configuration
# values and are not expected to change while the program runs.


# ============================================================
# 6.1 CURRENT TECHNOLOGY STACK
# ============================================================

HOME_TECHNOLOGY_STACK = [  # List concept: an ordered collection of multiple string values.
    "Django 5.2 + PostgreSQL + Django REST Framework",  # String value describing the backend technology.
    "React + Bootstrap 5 + Chart.js",  # String value describing frontend technology.
    "Alpaca Market Data + pandas + NumPy",  # String value describing market-data and analytical libraries.
    "MATLAB Integration",  # String value describing optional analytical integration.
    "Mailjet Email & Password Recovery",  # String value describing the configured email/password-recovery feature in this version of the code.
]


# ============================================================
# 6.2 CORE APPLICATION FEATURES
# ============================================================

HOME_CORE_FEATURES = [  # List: stores several dictionaries representing Home-page features.
    {  # Dictionary concept: stores related information as key/value pairs.
        "name":  # Dictionary key: identifies the feature-name value.
            "Dashboard",  # String value stored under the name key.
        "description":  # Dictionary key: identifies the description value.
            (  # Parentheses allow a long Python string to be split across source-code lines.
                "Monitor strategies, backtests, live market "
                "information and alerts from one central "
                "MarketPulse workspace."
            ),
    },
    {
        "name":
            "Market Data",
        "description":
            (
                "Explore Alpaca market data, historical OHLCV "
                "prices, charts and changing market conditions "
                "for research and analysis."
            ),
    },
    {
        "name":
            "Strategies",
        "description":
            (
                "Build and backtest trading strategies, compare "
                "results and examine robustness instead of "
                "relying on apparently perfect historical "
                "performance."
            ),
    },
    {
        "name":
            "Risk Management",
        "description":
            (
                "Plan position size, stop-loss levels and "
                "reward-to-risk before committing capital "
                "to a trading decision."
            ),
    },
]


# ============================================================
# 6.3 ABOUT MARKETPULSE
# ============================================================

HOME_ABOUT_DESCRIPTION = (  # Constant string: supplies the Home page About description.
    "MarketPulse is an educational trading decision-support "
    "platform designed to help users research financial "
    "markets, test trading strategies, evaluate risk, monitor "
    "changing market conditions and communicate with other "
    "users. The platform focuses on supporting better trading "
    "decisions rather than simply displaying price charts or "
    "historical backtest results."
)


# ============================================================
# 6.4 MARKETPULSE PURPOSE SUMMARY
# ============================================================

HOME_PURPOSE_SUMMARY = (  # Constant string: gives the Home page a compact summary of the application's purpose.
    "Research • Test • Analyse • Manage Risk • Communicate"
)


# ============================================================
# 6.5 COMPLETE FEATURE GUIDE
# ============================================================

HOME_FEATURE_GUIDE = [  # List of dictionaries: structured data later passed into home.html.
    {
        "name":
            "Dashboard",
        "description":
            (
                "Central workspace for strategies, backtests, "
                "live market information, monitoring and "
                "user alerts."
            ),
    },
    {
        "name":
            "Data",
        "description":
            (
                "Uses Alpaca market data to explore assets, "
                "historical OHLCV prices, charts and changing "
                "market conditions."
            ),
    },
    {
        "name":
            "Strategies",
        "description":
            (
                "Build, backtest and compare trading strategies "
                "while checking robustness and possible "
                "overfitting."
            ),
    },
    {
        "name":
            "Risk",
        "description":
            (
                "Supports trade planning through position "
                "sizing, stop-loss analysis and reward-to-risk "
                "calculations."
            ),
    },
    {
        "name":
            "Community",
        "description":
            (
                "Share market updates, trading warnings, risk "
                "alerts, observations, ideas and discussions "
                "with other MarketPulse users."
            ),
    },
    {
        "name":
            "Inbox",
        "description":
            (
                "Private user-to-user messaging with received "
                "messages, sent messages and unread-message "
                "tracking."
            ),
    },
    {
        "name":
            "Profile",
        "description":
            (
                "Manage personal account information, trading "
                "preferences and individual risk settings."
            ),
    },
    {
        "name":
            "Account Security",
        "description":
            (
                "Supports secure authentication, password "
                "changes and email-based password recovery "
                "through Django authentication and Mailjet."
            ),
    },
]


# ============================================================
# 6.6 EDUCATIONAL NOTICE
# ============================================================

HOME_EDUCATIONAL_NOTICE = (  # Constant string: keeps the educational-use disclaimer in the view configuration.
    "MarketPulse is an educational and decision-support "
    "application. Market information, backtesting results, "
    "strategy analysis, community posts and private messages "
    "should not be interpreted as personalised financial or "
    "investment advice."
)


# ============================================================
# 7. DASHBOARD CONFIGURATION
# ============================================================

DASHBOARD_BENCHMARKS = {  # Dictionary: maps each ticker symbol to a readable benchmark name.
    "SPY":  # Dictionary key: ticker symbol.
        "S&P 500 ETF",  # Dictionary value: human-readable description.
    "QQQ":
        "Nasdaq-100 ETF",
    "DIA":
        "Dow Jones ETF",
    "IWM":
        "Russell 2000 ETF",
}

DASHBOARD_CHART_LIMIT = 60  # Integer constant: limits how many stored historical rows are initially used for the Dashboard chart.
DASHBOARD_REFRESH_SECONDS = 60  # Integer constant: defines the browser refresh interval for current Alpaca information.


# ============================================================
# 8. HOME PAGE VIEW
# ============================================================

def home(  # Function definition concept: creates a reusable block of code called home.
    request,  # Function parameter: Django passes the current HttpRequest object into the view.
):
    """
    Render the MarketPulse landing page.

    The Home page combines:

    - MarketPulse purpose
    - Current technology stack
    - Core application features
    - Community activity
    - Inbox preview
    - Complete feature guide
    - Educational notice

    Public visitors can see:

    - platform information
    - feature descriptions
    - recent Community activity

    Authenticated users can additionally see:

    - recent private messages
    - unread private message count

    Actual post creation and private-message management remain
    inside community/views.py.
    """

    # ========================================================
    # 8.1 RECENT COMMUNITY POSTS
    # ========================================================

    recent_posts = (  # Variable assignment: stores the QuerySet returned by the ORM.
        CommunityPost.objects  # Django ORM manager: begins a database query against CommunityPost.
        .select_related(  # ORM optimisation: retrieves the related author in the same SQL query.
            "author"  # Relationship name: CommunityPost.author.
        )
        .order_by(  # QuerySet method: sorts the database results.
            "-created_at"  # Minus prefix means newest records appear first.
        )[:4]  # QuerySet slicing: returns only the first four records.
    )

    # ========================================================
    # 8.2 DEFAULT PRIVATE-INBOX VALUES
    # ========================================================

    recent_messages = (  # Variable assignment: creates a safe default for anonymous visitors.
        PrivateMessage.objects.none()  # ORM method: creates an empty QuerySet without retrieving messages.
    )
    unread_messages = 0  # Integer assignment: anonymous users begin with zero unread private messages.

    # ========================================================
    # 8.3 AUTHENTICATED USER INBOX
    # ========================================================

    if request.user.is_authenticated:  # Conditional statement: this block runs only when the request belongs to a logged-in user.
        recent_messages = (  # Variable reassignment: replace the empty QuerySet with the user's messages.
            PrivateMessage.objects  # ORM manager: starts a query against PrivateMessage.
            .filter(  # QuerySet filtering: restricts which database rows are returned.
                recipient=request.user  # Security condition: only messages addressed to the logged-in user are selected.
            )
            .select_related(  # ORM optimisation: retrieves sender information in the same query.
                "sender"  # Foreign-key relationship being loaded.
            )
            .order_by(  # ORM ordering: controls the order returned from PostgreSQL.
                "-created_at"  # Newest messages appear first.
            )[:4]  # QuerySet slice: Home page displays only the newest four messages.
        )

        unread_messages = (  # Assignment: stores the number of unread messages.
            PrivateMessage.objects  # ORM manager: starts another PrivateMessage query.
            .filter(  # ORM filter: applies multiple database conditions.
                recipient=request.user,  # Security condition: message must belong to current user.
                is_read=False,  # Boolean condition: only unread messages are included.
            )
            .count()  # ORM aggregation method: asks the database to count matching records.
        )

    # ========================================================
    # 8.4 HOME TEMPLATE CONTEXT
    # ========================================================

    context = {  # Dictionary concept: creates the named data passed from the Django view to home.html.
        "home_technology_stack":  # Template context key.
            HOME_TECHNOLOGY_STACK,  # Context value: technology-stack list.
        "home_core_features":
            HOME_CORE_FEATURES,
        "home_about_description":
            HOME_ABOUT_DESCRIPTION,
        "home_purpose_summary":
            HOME_PURPOSE_SUMMARY,
        "home_feature_guide":
            HOME_FEATURE_GUIDE,
        "home_educational_notice":
            HOME_EDUCATIONAL_NOTICE,
        "recent_posts":
            recent_posts,
        "recent_messages":
            recent_messages,
        "unread_messages":
            unread_messages,
        "unread_message_count":
            unread_messages,  # Same value is provided under a second descriptive context name.
    }

    # ========================================================
    # 8.5 RENDER HOME TEMPLATE
    # ========================================================

    return render(  # Return statement: ends the function and gives Django an HttpResponse.
        request,  # Current browser request.
        "home.html",  # Template file Django should render.
        context,  # Dictionary of data available inside the template.
    )


# ============================================================
# 9. SELECT DASHBOARD MARKET SYMBOL
# ============================================================

def _get_selected_dashboard_symbol(  # Helper function: leading underscore signals that this function is intended for internal use in this module.
    request,  # HttpRequest parameter containing URL query-string data.
):
    """
    Read the selected Dashboard benchmark from the URL.

    Examples:

        /dashboard/?symbol=SPY
        /dashboard/?symbol=QQQ

    This helper controls the traditional benchmark context used
    by the Django-rendered Dashboard.

    The interactive stock-search workspace can load arbitrary
    symbols independently through JavaScript and the Alpaca API.
    """

    symbol = (  # Variable assignment: stores the cleaned ticker symbol.
        request.GET  # Django QueryDict: contains values from the URL query string.
        .get(  # Dictionary-like method: returns one query-string value.
            "symbol",  # Query-string key to read.
            "SPY",  # Default value when symbol is missing.
        )
        .strip()  # String method: removes spaces from both ends.
        .upper()  # String method: converts the ticker to uppercase.
    )

    if (  # Conditional statement: validates the selected ticker.
        symbol
        not in  # Membership operator: checks whether the ticker is absent from the dictionary.
        DASHBOARD_BENCHMARKS
    ):
        symbol = (  # Assignment: invalid values fall back to SPY.
            "SPY"
        )

    return symbol  # Return statement: gives the validated ticker back to the calling function.


# ============================================================
# 10. AVAILABLE HISTORICAL CHART SYMBOLS
# ============================================================

def _get_available_chart_symbols():  # Helper function: no arguments are required.
    """
    Return benchmark symbols that already have historical
    MarketData observations stored in PostgreSQL.

    This remains useful for:

    - fallback historical charts
    - data-health information
    - strategy testing
    - Market Condition analysis

    Live Alpaca graph availability is handled separately by the
    API layer.
    """

    stored_symbols = set(  # Built-in set concept: stores unique ticker symbols for fast membership checking.
        MarketData.objects  # ORM manager: begins a MarketData query.
        .filter(  # QuerySet filtering: restricts records to supported Dashboard benchmarks.
            symbol__in=list(  # Django __in lookup: SQL equivalent of WHERE symbol IN (...).
                DASHBOARD_BENCHMARKS.keys()  # Dictionary method: returns the benchmark ticker keys.
            )
        )
        .values_list(  # ORM projection: asks PostgreSQL for only one column rather than complete model objects.
            "symbol",  # Database/model field being selected.
            flat=True,  # flat=True returns a simple sequence instead of one-item tuples.
        )
        .distinct()  # SQL DISTINCT concept: removes duplicate ticker values.
    )

    return [  # List comprehension concept: creates a new list from an iterable with a condition.
        symbol  # Value to place into the returned list.
        for symbol  # Loop portion of the comprehension.
        in DASHBOARD_BENCHMARKS  # Iterates through configured benchmark dictionary keys.
        if symbol in stored_symbols  # Filter condition: keeps only symbols that exist in PostgreSQL.
    ]


# ============================================================
# 11. HISTORICAL POSTGRESQL CHART DATA
# ============================================================

def _get_dashboard_chart_rows(  # Helper function: retrieves stored observations for the Dashboard.
    symbol,  # Parameter: ticker whose observations should be retrieved.
    limit=DASHBOARD_CHART_LIMIT,  # Default parameter concept: uses 60 unless another limit is supplied.
):
    """
    Retrieve stored historical OHLCV observations from the
    MarketData table.

    MarketData records are selected newest-first so the most
    recent observations can be limited efficiently.

    They are then reversed because charting libraries normally
    expect chronological ordering:

        oldest
            ↓
        newest
    """

    rows = list(  # Built-in list conversion: evaluates the QuerySet and stores model objects in a Python list.
        MarketData.objects  # ORM manager: begins a query against MarketData.
        .filter(  # QuerySet filter: restricts rows to one ticker.
            symbol=symbol  # Field lookup: SQL equivalent of WHERE symbol = selected ticker.
        )
        .order_by(  # ORM ordering: retrieves newest records first.
            "-date"  # Minus means descending date order.
        )[:limit]  # QuerySet slicing: SQL LIMIT equivalent.
    )

    rows.reverse()  # List method: changes newest→oldest into oldest→newest for chart display.

    return [  # List comprehension: converts Django model objects into plain dictionaries.
        {  # Dictionary: one browser-friendly market observation.
            "date":
                row.date.isoformat(),  # Method call: converts Python date into an ISO string such as 2026-10-07.
            "open_price":
                float(  # Type conversion: Decimal/database value becomes a JSON-friendly Python float.
                    row.open_price
                ),
            "high_price":
                float(
                    row.high_price
                ),
            "low_price":
                float(
                    row.low_price
                ),
            "close_price":
                float(
                    row.close_price
                ),
            "volume":
                row.volume,  # Attribute access: reads the volume field directly from the model instance.
        }
        for row  # List-comprehension loop variable.
        in rows  # Iterable: the historical model objects retrieved above.
    ]


# ============================================================
# 12. LATEST MARKET CONDITION
# ============================================================

def _get_latest_market_condition(  # Helper function: retrieves the latest analytical regime result for a ticker.
    symbol,  # Parameter: ticker being analysed.
):
    """
    Retrieve the newest stored Market Condition analysis for the
    selected Dashboard benchmark.

    MarketRegime belongs to the internal analytics layer.

    The Dashboard surfaces only the most recent result so the
    user receives useful market context without exposing a
    separate Analysis application.
    """

    regime = (  # Variable assignment: will hold a MarketRegime object or None.
        MarketRegime.objects  # ORM manager: begins query against the analytics model.
        .filter(  # QuerySet filter: keeps rows matching the selected ticker.
            symbol=symbol  # Field equality lookup.
        )
        .order_by(  # QuerySet ordering: newest analytical result should appear first.
            "-date",  # Primary descending sort by market date.
            "-created_at",  # Secondary descending sort by database creation time.
        )
        .first()  # QuerySet method: returns the first result or None.
    )

    if regime is None:  # Identity comparison: checks specifically for the Python None object.
        return None  # Early return: no Market Condition exists for this ticker.

    try:  # Exception-handling concept: attempt code that may not exist on every model implementation.
        display_name = (  # Assignment: human-readable regime label.
            regime.get_regime_display()  # Django model method automatically generated for fields using choices.
        )
    except AttributeError:  # Exception handler: runs if get_regime_display does not exist.
        display_name = (  # Fallback assignment.
            regime.regime  # Raw stored regime value.
        )

    return {  # Dictionary: converts the model result into simple Dashboard context data.
        "id":
            regime.pk,  # Primary-key attribute.
        "symbol":
            regime.symbol,  # Model field.
        "date":
            regime.date,  # Model date field.
        "regime":
            regime.regime,  # Raw classification value.
        "display":
            display_name,  # Human-readable classification value.
        "confidence":
            (  # Conditional expression: returns a float only when a value exists.
                float(
                    regime.confidence
                )
                if regime.confidence is not None
                else None
            ),
        "volatility":
            (
                float(
                    regime.volatility
                )
                if regime.volatility is not None
                else None
            ),
        "trend_strength":
            (
                float(
                    regime.trend_strength
                )
                if regime.trend_strength is not None
                else None
            ),
    }


# ============================================================
# 13. MARKET DATA HEALTH
# ============================================================

def _get_market_data_health():  # Helper function: calculates summary information about all stored market data.
    """
    Summarise the historical MarketData currently stored in
    PostgreSQL.

    This provides the Dashboard with information about:

    - total observations
    - number of stored symbols
    - earliest historical observation
    - latest historical observation
    - approximate data staleness
    """

    total_rows = (  # Assignment: stores total MarketData observation count.
        MarketData.objects  # ORM manager.
        .count()  # SQL COUNT operation.
    )

    stored_symbol_count = (  # Assignment: stores number of unique symbols.
        MarketData.objects  # ORM manager.
        .values(  # ORM projection: requests only the symbol field.
            "symbol"
        )
        .distinct()  # SQL DISTINCT: removes duplicate symbols.
        .count()  # Counts unique symbol rows.
    )

    latest_date = (  # Assignment: newest date currently stored.
        MarketData.objects  # ORM manager.
        .order_by(  # ORM sorting.
            "-date"  # Descending means newest first.
        )
        .values_list(  # Returns only the selected column.
            "date",  # Column/model field.
            flat=True,  # Return simple date values.
        )
        .first()  # Take the newest date or None.
    )

    earliest_date = (  # Assignment: oldest stored observation date.
        MarketData.objects  # ORM manager.
        .order_by(  # ORM sorting.
            "date"  # Ascending means oldest first.
        )
        .values_list(  # Projection: only retrieve date.
            "date",
            flat=True,
        )
        .first()
    )

    days_since_latest = None  # None concept: represents the absence of a calculated staleness value.

    if latest_date:  # Truth-value condition: run only if a latest date exists.
        days_since_latest = (  # Assignment: calculate number of calendar days since the newest observation.
            timezone.localdate()  # Django helper: today's date in the configured application timezone.
            -
            latest_date  # Date arithmetic: subtract stored date from current date.
        ).days  # timedelta attribute: extracts the integer number of days.

    return {  # Dictionary: returns the complete data-health summary.
        "total_rows":
            total_rows,
        "stored_symbols":
            stored_symbol_count,
        "earliest_date":
            earliest_date,
        "latest_date":
            latest_date,
        "days_since_latest":
            days_since_latest,
    }


# ============================================================
# 14. ALERT CHOICE HELPERS
# ============================================================

def _get_alert_type_choices():  # Helper function: reads configured alert-type choices from model metadata.
    """
    Read Alert alert_type choices directly from Django's model
    field metadata.

    This avoids depending on a particular Python constant such
    as Alert.ALERT_TYPES because the current model defines its
    configured choices through the field.
    """

    return (  # Return statement: sends Django's choices object back to the caller.
        Alert._meta  # Django model metadata API.
        .get_field(  # Metadata method: retrieves one model field definition.
            "alert_type"  # Name of the field.
        )
        .choices  # Field property: returns its configured choices.
    )


def _get_alert_severity_choices():  # Helper function: reads severity options from model metadata.
    """
    Read severity choices directly from the Alert model field.

    The Edit Alert interface can therefore remain aligned with
    the actual model configuration.
    """

    return (
        Alert._meta  # Django model metadata object.
        .get_field(  # Finds the field definition.
            "severity"  # Field name being inspected.
        )
        .choices  # Returns configured severity choices.
    )


# ============================================================
# 15. DASHBOARD VIEW
# ============================================================

@login_required  # Decorator: unauthenticated users are redirected to LOGIN_URL before this function can run.
def dashboard(  # Function definition: authenticated Dashboard controller.
    request,  # HttpRequest object supplied by Django.
):
    """
    Render the authenticated MarketPulse Dashboard.

    Framework mapping:

    Browser
        ↓
    dashboard()
        ↓
    Django ORM
        ↓
    PostgreSQL
        ↓
    dashboard.html
        ↓
    JavaScript
        ↓
    MarketPulse REST API
        ↓
    Alpaca

    The page combines:

    - user strategies
    - backtests
    - historical PostgreSQL data
    - Market Condition analysis
    - generated Alerts
    - configurable AlertRules
    - Alpaca live market information
    """

    # ========================================================
    # 15.1 USER STRATEGIES
    # ========================================================

    strategies = (  # Assignment: QuerySet containing strategies belonging to the current authenticated user.
        Strategy.objects  # ORM manager for Strategy.
        .filter(  # Security/user filtering.
            user=request.user  # Foreign-key equality: only this user's strategies.
        )
        .order_by(  # Sort strategy records.
            "-created_at"  # Newest first.
        )
    )

    active_strategies = (  # QuerySet refinement: starts from the strategies QuerySet above.
        strategies
        .filter(  # Additional SQL condition.
            is_active=True  # Boolean filter: only active strategies.
        )
    )

    # ========================================================
    # 15.2 USER BACKTESTS
    # ========================================================

    backtests = (  # Assignment: retrieves backtests connected to the current user's strategies.
        Backtest.objects  # ORM manager.
        .filter(  # Relationship traversal using Django's double-underscore syntax.
            strategy__user=request.user  # Follow Backtest.strategy → Strategy.user.
        )
        .select_related(  # ORM optimisation: retrieve associated Strategy in same SQL query.
            "strategy"
        )
        .order_by(  # Sort result set.
            "-created_at"  # Newest backtests first.
        )
    )

    latest_backtest = (  # Assignment: newest Backtest object or None.
        backtests.first()  # QuerySet method: retrieves first item.
    )

    # ========================================================
    # 15.3 AVERAGE WIN RATE
    # ========================================================

    average_win_rate = (  # Assignment: stores aggregated average or zero.
        backtests
        .aggregate(  # ORM aggregate concept: calculates one summary value across many rows.
            value=Avg(  # Avg database function.
                "win_rate"  # Model field being averaged.
            )
        )
        .get(  # Dictionary method: reads result generated under alias "value".
            "value"
        )
        or  # Boolean operator: use zero when database result is None/falsy.
        0
    )

    average_win_rate_pct = (  # Assignment: converts stored decimal proportion into percentage.
        float(  # Type conversion: database numeric value becomes Python float.
            average_win_rate
        )
        *
        100  # Arithmetic multiplication: for example 0.55 becomes 55.
    )

    # ========================================================
    # 15.4 GENERATED USER ALERTS
    # ========================================================

    alerts = (  # Assignment: QuerySet of Alerts owned by current user.
        Alert.objects  # ORM manager.
        .filter(  # Security filtering.
            user=request.user  # Only current user's alerts.
        )
        .order_by(  # Multi-field sorting.
            "-is_active",  # Active alerts first.
            "-created_at",  # Then newest alerts first.
        )
    )

    active_alerts = (  # QuerySet derived from alerts.
        alerts
        .filter(  # Additional filtering.
            is_active=True  # Only unresolved/active alerts.
        )
    )

    unread_alerts = (  # QuerySet derived from alerts.
        alerts
        .filter(  # Additional filtering.
            is_read=False  # Only alerts not yet acknowledged.
        )
    )

    # ========================================================
    # 15.5 CONFIGURABLE ALERT RULES
    # ========================================================

    alert_rules = (  # Assignment: all monitoring rules belonging to current user.
        AlertRule.objects  # ORM manager.
        .filter(  # Security filtering.
            user=request.user  # Only current user's rules.
        )
        .order_by(  # Multi-column ordering.
            "-is_enabled",  # Enabled rules first.
            "symbol",  # Then alphabetically by ticker.
            "metric",  # Then by monitored metric.
            "-created_at",  # Newest rules first within otherwise-equal groups.
        )
    )

    enabled_alert_rules = (  # QuerySet containing only enabled rules.
        alert_rules
        .filter(  # Additional filtering.
            is_enabled=True  # Boolean field condition.
        )
    )

    alert_rule_form = (  # Assignment: empty Django form used for creating a new rule.
        AlertRuleForm()  # Class instantiation concept: creates a form object.
    )

    # ========================================================
    # 15.6 GENERATED ALERT FORM OPTIONS
    # ========================================================

    alert_type_choices = (  # Assignment: retrieves model-configured alert-type options.
        _get_alert_type_choices()  # Helper-function call.
    )

    alert_severity_choices = (  # Assignment: retrieves model-configured severity options.
        _get_alert_severity_choices()  # Helper-function call.
    )

    # ========================================================
    # 15.7 SELECT DEFAULT MARKET BENCHMARK
    # ========================================================

    selected_symbol = (  # Assignment: stores validated Dashboard ticker.
        _get_selected_dashboard_symbol(  # Helper-function call.
            request  # Pass current HTTP request into helper.
        )
    )

    # ========================================================
    # 15.8 STORED POSTGRESQL HISTORICAL GRAPH DATA
    # ========================================================

    chart_rows = (  # Assignment: browser-friendly stored historical observations.
        _get_dashboard_chart_rows(  # Helper-function call.
            selected_symbol  # Argument: ticker chosen above.
        )
    )

    available_chart_symbols = (  # Assignment: benchmark tickers that currently have stored MarketData.
        _get_available_chart_symbols()  # Helper-function call with no arguments.
    )

    # ========================================================
    # 15.9 MARKET CONDITION
    # ========================================================

    market_condition = (  # Assignment: latest MarketRegime summary for selected ticker.
        _get_latest_market_condition(  # Helper call.
            selected_symbol  # Argument.
        )
    )

    # ========================================================
    # 15.10 DATA HEALTH
    # ========================================================

    data_health = (  # Assignment: stores global MarketData statistics.
        _get_market_data_health()  # Helper-function call.
    )

    # ========================================================
    # 15.11 DASHBOARD TEMPLATE CONTEXT
    # ========================================================

    context = {  # Dictionary: all values that dashboard.html can use.
        "active_strategy_count":
            active_strategies.count(),  # ORM count: number of active strategies.
        "strategy_count":
            strategies.count(),  # ORM count: number of all user strategies.
        "backtest_count":
            backtests.count(),  # ORM count: number of user's backtests.
        "avg_win_rate":
            average_win_rate_pct,  # Python numeric value already converted to percentage.
        "market_data_count":
            data_health[
                "total_rows"
            ],  # Dictionary indexing: retrieve total_rows from data_health.
        "strategies":
            strategies,  # QuerySet available to dashboard template.
        "latest_backtest":
            latest_backtest,  # One model object or None.
        "recent_backtests":
            backtests[:5],  # QuerySet slicing: only five newest backtests.
        "alerts":
            alerts,  # QuerySet of generated alerts.
        "active_alerts":
            active_alerts,  # QuerySet of active alerts.
        "active_alert_count":
            active_alerts.count(),  # ORM count.
        "unread_alert_count":
            unread_alerts.count(),  # ORM count.
        "alert_type_choices":
            alert_type_choices,  # Model metadata choices.
        "alert_severity_choices":
            alert_severity_choices,  # Model metadata choices.
        "alert_rules":
            alert_rules,  # QuerySet of configurable monitoring rules.
        "alert_rule_count":
            alert_rules.count(),  # ORM count.
        "enabled_alert_rules":
            enabled_alert_rules,  # QuerySet of enabled monitoring rules.
        "enabled_alert_rule_count":
            enabled_alert_rules.count(),  # ORM count.
        "alert_rule_form":
            alert_rule_form,  # Django form object.
        "dashboard_benchmarks":
            DASHBOARD_BENCHMARKS,  # Dictionary constant.
        "selected_symbol":
            selected_symbol,  # Current ticker string.
        "available_chart_symbols":
            available_chart_symbols,  # Python list.
        "market_chart_rows":
            chart_rows,  # Python list of dictionaries.
        "market_chart_has_data":
            bool(  # Type conversion: converts the list into True when it contains rows and False when empty.
                chart_rows
            ),
        "market_condition":
            market_condition,  # Dictionary or None.
        "data_health":
            data_health,  # Dictionary containing MarketData statistics.
        "dashboard_refresh_seconds":
            DASHBOARD_REFRESH_SECONDS,  # Integer configuration constant.
    }

    # ========================================================
    # 15.12 RENDER DASHBOARD
    # ========================================================

    return render(  # Django rendering shortcut.
        request,  # Current request.
        "dashboard.html",  # Template name.
        context,  # Context dictionary.
    )


# ============================================================
# 16. EDIT GENERATED ALERT
# ============================================================

@login_required  # Authentication decorator: login required.
@require_POST  # HTTP-method decorator: GET requests cannot perform this modifying action.
def edit_alert(  # View function: updates one generated Alert.
    request,  # Current HTTP request.
    alert_id,  # URL parameter: database primary key supplied by the route.
):
    """
    Update an Alert notification belonging to the authenticated
    user.

    This edits the generated notification itself.

    It does NOT alter an AlertRule monitoring condition.

    Security:

        user=request.user

    prevents a user from editing another user's alert simply by
    changing the numeric identifier in the URL.
    """

    alert = get_object_or_404(  # Secure object lookup: missing or unauthorised object returns HTTP 404.
        Alert,  # Model class being queried.
        pk=alert_id,  # Primary-key lookup from the URL.
        user=request.user,  # Authorization condition: Alert must belong to current user.
    )

    form = AlertEditForm(  # Form-class instantiation: binds submitted POST data to existing Alert.
        request.POST,  # QueryDict containing submitted form fields.
        instance=alert,  # ModelForm concept: update this existing database object instead of creating a new one.
    )

    if form.is_valid():  # Conditional statement: continue only if Django form validation succeeds.
        updated_alert = (  # Assignment: stores saved Alert object.
            form.save()  # ModelForm CRUD operation: writes validated changes to database.
        )

        messages.success(  # Django messages framework: creates one-time success notification.
            request,  # Current request/session.
            (
                f'Alert "{updated_alert.title}" '  # f-string concept: embeds a Python value inside a string.
                f"was updated successfully."
            ),
        )
    else:  # Branch statement: runs when validation fails.
        messages.error(  # One-time error notification.
            request,
            (
                "The alert could not be updated. "
                "Please check the submitted values."
            ),
        )

    return redirect(  # Post/Redirect/Get workflow: send browser back to Dashboard after modification.
        "dashboard"  # Named Django URL route.
    )


# ============================================================
# 17. MARK GENERATED ALERT AS READ
# ============================================================

@login_required  # Authentication decorator.
@require_POST  # Security/HTTP semantics: state-changing action must use POST.
def mark_alert_read(  # View function definition.
    request,  # HttpRequest parameter.
    alert_id,  # URL-supplied Alert primary key.
):
    """
    Acknowledge a generated Alert notification.
    """

    alert = get_object_or_404(  # Secure lookup.
        Alert,  # Model being queried.
        pk=alert_id,  # Primary-key condition.
        user=request.user,  # Ownership condition.
    )

    alert.mark_as_read()  # Object-oriented programming: calls a model method encapsulating read-state behaviour.

    messages.success(  # Django message framework.
        request,  # Current request.
        f'Alert "{alert.title}" was marked as read.',  # f-string with Alert title.
    )

    return redirect(  # Redirect response.
        "dashboard"  # Named URL.
    )


# ============================================================
# 18. TOGGLE GENERATED ALERT RESOLUTION
# ============================================================

@login_required  # Authentication decorator.
@require_POST  # Only POST requests may modify alert state.
def toggle_alert_resolution(  # View controlling resolve/reopen behaviour.
    request,  # HttpRequest.
    alert_id,  # URL parameter.
):
    """
    Resolve an active generated Alert or reopen a previously
    resolved Alert.
    """

    alert = get_object_or_404(  # Secure database retrieval.
        Alert,  # Model class.
        pk=alert_id,  # Primary-key condition.
        user=request.user,  # Authorization condition.
    )

    if alert.is_active:  # Conditional statement: determine current Alert state.
        alert.resolve()  # Object method: encapsulates transition from active to resolved.

        messages.success(  # Success flash message.
            request,
            f'Alert "{alert.title}" was resolved.',  # f-string.
        )
    else:  # Opposite branch: Alert is already inactive/resolved.
        alert.reopen()  # Object method: reactivates the Alert.

        messages.info(  # Informational flash message.
            request,
            f'Alert "{alert.title}" was reopened.',  # f-string.
        )

    return redirect(  # Return redirect response.
        "dashboard"  # Redirect to named Dashboard route.
    )


# ============================================================
# 19. CREATE ALERT RULE
# ============================================================

@login_required  # Authentication decorator.
@require_POST  # Only POST can create a database object.
def create_alert_rule(  # View function for AlertRule creation.
    request,  # Current request.
):
    """
    Create a configurable market-monitoring rule.
    """

    form = (  # Assignment: bind submitted data to AlertRuleForm.
        AlertRuleForm(  # Class instantiation.
            request.POST  # Submitted HTML form data.
        )
    )

    if form.is_valid():  # Form-validation condition.
        alert_rule = (  # Assignment: unsaved model object.
            form.save(  # ModelForm save method.
                commit=False  # Parameter: create object in memory but do not write it to database yet.
            )
        )

        alert_rule.user = (  # Attribute assignment: connect the new rule to authenticated user.
            request.user  # Current User object.
        )

        alert_rule.save()  # Model save method: inserts the completed object into PostgreSQL.

        messages.success(  # Flash success notification.
            request,
            (
                f'Alert rule for "{alert_rule.symbol}" '
                f"was created successfully."
            ),
        )
    else:  # Validation-failure branch.
        messages.error(  # Flash error notification.
            request,
            (
                "The alert rule could not be created. "
                "Please check the submitted values."
            ),
        )

    return redirect(  # Redirect after POST.
        "dashboard"
    )


# ============================================================
# 20. EDIT ALERT RULE
# ============================================================

@login_required  # Requires authenticated user.
@require_POST  # Requires POST because database state will change.
def edit_alert_rule(  # View function for modifying a monitoring rule.
    request,  # HttpRequest.
    rule_id,  # URL parameter containing AlertRule primary key.
):
    """
    Modify an existing AlertRule owned by the current user.
    """

    alert_rule = (  # Assignment: retrieve authorised rule.
        get_object_or_404(  # Django shortcut.
            AlertRule,  # Model being queried.
            pk=rule_id,  # Primary-key lookup.
            user=request.user,  # Authorization check through database filter.
        )
    )

    form = (  # Assignment: create bound form for existing rule.
        AlertRuleForm(  # ModelForm constructor.
            request.POST,  # Submitted form values.
            instance=alert_rule,  # Existing model instance to update.
        )
    )

    if form.is_valid():  # Validate submitted values.
        updated_rule = (  # Assignment: store updated model object.
            form.save()  # UPDATE database operation through ModelForm.
        )

        messages.success(  # Flash success message.
            request,
            (
                f'Alert rule for "{updated_rule.symbol}" '
                f"was updated successfully."
            ),
        )
    else:  # Form-invalid branch.
        messages.error(  # Flash error message.
            request,
            (
                "The alert rule could not be updated. "
                "Please check the submitted values."
            ),
        )

    return redirect(  # Browser redirect.
        "dashboard"
    )


# ============================================================
# 21. ENABLE / DISABLE ALERT RULE
# ============================================================

@login_required  # Requires authenticated session.
@require_POST  # Restricts endpoint to POST.
def toggle_alert_rule(  # View toggling one Boolean rule property.
    request,  # HttpRequest.
    rule_id,  # URL primary-key parameter.
):
    """
    Toggle whether MarketPulse should actively evaluate an
    AlertRule.
    """

    alert_rule = (  # Assignment: authorised rule object.
        get_object_or_404(  # Django shortcut.
            AlertRule,  # Model class.
            pk=rule_id,  # Primary-key lookup.
            user=request.user,  # Ownership check.
        )
    )

    alert_rule.is_enabled = (  # Attribute assignment: replace current Boolean value.
        not  # Boolean NOT operator: reverses True to False or False to True.
        alert_rule.is_enabled  # Existing Boolean value.
    )

    alert_rule.save(  # Model method: write changed field back to database.
        update_fields=[  # List parameter: tell Django exactly which columns need updating.
            "is_enabled",  # Boolean state column.
            "updated_at",  # Timestamp column.
        ]
    )

    state = (  # Assignment using a conditional expression.
        "enabled"  # Value when condition is True.
        if alert_rule.is_enabled  # Inline if condition.
        else "disabled"  # Value when condition is False.
    )

    messages.info(  # Flash informational message.
        request,
        (
            f'{alert_rule.symbol} alert rule '
            f"was {state}."
        ),
    )

    return redirect(  # Redirect response.
        "dashboard"
    )


# ============================================================
# 22. DELETE ALERT RULE
# ============================================================

@login_required  # Authentication decorator.
@require_POST  # State-changing deletion endpoint accepts POST only.
def delete_alert_rule(  # View function responsible for deleting one monitoring rule.
    request,  # HttpRequest.
    rule_id,  # URL-supplied rule primary key.
):
    """
    Permanently delete a monitoring AlertRule.

    Existing generated Alert records are intentionally
    preserved.
    """

    alert_rule = (  # Assignment: securely retrieve rule.
        get_object_or_404(  # Django shortcut.
            AlertRule,  # Model class.
            pk=rule_id,  # Primary-key filter.
            user=request.user,  # Authorization filter.
        )
    )

    symbol = (  # Assignment: preserve symbol before deleting the object.
        alert_rule.symbol  # Model attribute.
    )

    condition = (  # Assignment: preserve readable condition before deleting object.
        alert_rule.condition_display  # Model property or field containing readable condition.
    )

    alert_rule.delete()  # CRUD DELETE operation: removes this AlertRule row from PostgreSQL.

    messages.success(  # Flash success notification.
        request,
        (
            f"{symbol} alert rule "  # f-string uses value saved before deletion.
            f"({condition}) was deleted."
        ),
    )

    return redirect(  # Redirect browser back to Dashboard.
        "dashboard"
    )