"""
============================================================
MARKETPULSE - CORE HOME / DASHBOARD VIEWS
============================================================

Framework mapping:

Browser
    ↓
marketpulse/urls.py
    ↓
core/views.py
    ↓
Django Forms / Django ORM
    ↓
PostgreSQL / Neon
    ↓
templates/home.html
templates/dashboard.html


============================================================
HOME PAGE PURPOSE
============================================================

The MarketPulse Home page introduces the current version of
the platform and provides a concise overview of the features
available to the user.

The Home page is divided into several areas:

1. MarketPulse hero / introduction
2. Current technology stack
3. Main application feature summary
4. Latest Community activity
5. Private Inbox preview
6. Compact About MarketPulse section
7. Educational-use notice


The Home page now represents the actual application rather
than the original MarketPulse project proposal.

MarketPulse currently focuses on:

    Research Markets
        ↓
    Market Data
        ↓
    Test Strategies
        ↓
    Backtesting / Robustness
        ↓
    Manage Trading Risk
        ↓
    Position Sizing / Stop-Loss / Reward-to-Risk
        ↓
    Monitor Conditions
        ↓
    Dashboard / Alerts
        ↓
    Communicate
        ↓
    Community / Inbox


============================================================
HOME PAGE FEATURE ARCHITECTURE
============================================================

The explanatory information displayed by home.html is defined
in this file using configuration constants.

This gives the project a cleaner architecture:

core/views.py
    ↓
Defines application content
    ↓
home()
    ↓
Template context
    ↓
templates/home.html


Instead of writing all feature explanations directly inside
the HTML template, the view can supply structured information
such as:

    HOME_TECHNOLOGY_STACK

    HOME_CORE_FEATURES

    HOME_FEATURE_GUIDE


This means future updates can be made in one place.


============================================================
COMMUNITY ARCHITECTURE
============================================================

CommunityPost
    ↓
Stores public MarketPulse posts


Community post examples:

    Market Update
    Trading Warning
    Risk Alert
    Trading Idea
    Discussion


The Home page displays only a preview.

The full Community functionality remains inside:

    community/views.py


Framework mapping:

CommunityPost
    ↓
core.views.home
    ↓
recent_posts
    ↓
templates/home.html
    ↓
Community Pulse Preview


============================================================
PRIVATE MESSAGING ARCHITECTURE
============================================================

PrivateMessage
    ↓
Stores private communication between MarketPulse users


Example:

    user2
        ↓
    user3


Subject:

    MSFT risk discussion


The Home page displays:

    - newest received messages
    - unread message count


The full Inbox remains inside:

    community/views.py


Framework mapping:

PrivateMessage
    ↓
core.views.home
    ↓
recent_messages
    ↓
unread_messages
    ↓
templates/home.html


============================================================
DASHBOARD PURPOSE
============================================================

The Dashboard is the user's high-level MarketPulse control
centre.

It summarises:

1. User strategies
2. Backtest activity
3. Average strategy win rate
4. Historical market-data storage
5. Current selected market benchmark
6. Stored historical chart data
7. Latest Market Condition
8. Persistent generated alerts
9. Configurable user alert rules
10. Unread alert count
11. Recent backtest activity


============================================================
ALERT ARCHITECTURE
============================================================

AlertRule
    ↓
Defines what MarketPulse should monitor


Example:

    SPY
    Price
    Greater Than
    800


Alert
    ↓
Represents an actual notification/event generated by
MarketPulse.


Example:

    "SPY moved above $800"


This distinction allows users to edit monitoring conditions
without rewriting historical alert records.


============================================================
LIVE MARKET DATA
============================================================

Current / recent Alpaca information is fetched through:

    /api/dashboard/market-overview/


The interactive professional chart can also request arbitrary
symbols through the Alpaca API endpoints.


The normal Django Dashboard view supplies PostgreSQL and user
information immediately so the page remains useful before
JavaScript finishes loading live market information.

============================================================
"""


# ============================================================
# 1. DJANGO IMPORTS
# ============================================================

from django.contrib import messages

from django.contrib.auth.decorators import login_required

from django.db.models import Avg

from django.shortcuts import (
    get_object_or_404,
    redirect,
    render,
)

from django.utils import timezone

from django.views.decorators.http import require_POST


# ============================================================
# 2. INTERNAL ANALYTICS
# ============================================================

# analysis_tools remains an internal analytical layer.
#
# Market Condition results are surfaced on the Dashboard and
# within the Data workflow rather than requiring a separate
# public Analysis navigation tab.

from analysis_tools.models import (
    MarketRegime,
)


# ============================================================
# 3. CORE MODELS
# ============================================================

from .models import (
    Alert,
    AlertRule,
    Backtest,
    MarketData,
    Strategy,
)


# ============================================================
# 3.1 CORE FORMS
# ============================================================

# AlertEditForm:
#
#     Edits an already-generated Alert record.
#
# AlertRuleForm:
#
#     Creates or modifies a monitoring condition configured
#     by the user.

from .forms import (
    AlertEditForm,
    AlertRuleForm,
)


# ============================================================
# 3.2 COMMUNITY MODELS
# ============================================================

# CommunityPost:
#
#     Stores user-generated MarketPulse Community posts such
#     as market updates, trading warnings, risk alerts,
#     trading ideas and discussions.
#
#
# PrivateMessage:
#
#     Stores private messages sent from one authenticated
#     MarketPulse user to another.
#
#
# These models belong to the community application rather than
# core because social communication is a separate application
# area from MarketPulse trading analytics.

from community.models import (
    CommunityPost,
    PrivateMessage,
)


# ============================================================
# 4. HOME PAGE CONFIGURATION
# ============================================================

# The following configuration structures describe the current
# MarketPulse application.
#
# They are supplied to home.html through the home() context.
#
# This avoids duplicating application descriptions throughout
# the template and makes future project updates easier.


# ============================================================
# 4.1 CURRENT TECHNOLOGY STACK
# ============================================================

HOME_TECHNOLOGY_STACK = [

    "Django 5.2 + PostgreSQL + Django REST Framework",

    "React + Bootstrap 5 + Chart.js",

    "Alpaca Market Data + pandas + NumPy",

    "MATLAB Integration",

    "Mailjet Email & Password Recovery",

]


# ============================================================
# 4.2 CORE APPLICATION FEATURES
# ============================================================

# These correspond to the four principal analytical areas
# displayed directly beneath the MarketPulse Home hero.

HOME_CORE_FEATURES = [


    # --------------------------------------------------------
    # DASHBOARD
    # --------------------------------------------------------

    {

        "name":
            "Dashboard",

        "description":
            (
                "Monitor strategies, backtests, live market "
                "information and alerts from one central "
                "MarketPulse workspace."
            ),

    },


    # --------------------------------------------------------
    # MARKET DATA
    # --------------------------------------------------------

    {

        "name":
            "Market Data",

        "description":
            (
                "Explore Alpaca market data, historical OHLCV "
                "prices, charts and changing market conditions "
                "for research and analysis."
            ),

    },


    # --------------------------------------------------------
    # STRATEGIES
    # --------------------------------------------------------

    {

        "name":
            "Strategies",

        "description":
            (
                "Build and backtest trading strategies, compare "
                "results and examine robustness instead of "
                "relying on apparently perfect historical "
                "performance."
            ),

    },


    # --------------------------------------------------------
    # RISK MANAGEMENT
    # --------------------------------------------------------

    {

        "name":
            "Risk Management",

        "description":
            (
                "Plan position size, stop-loss levels and "
                "reward-to-risk before committing capital "
                "to a trading decision."
            ),

    },

]


# ============================================================
# 4.3 ABOUT MARKETPULSE
# ============================================================

HOME_ABOUT_DESCRIPTION = (
    "MarketPulse is an educational trading decision-support "
    "platform designed to help users research financial "
    "markets, test trading strategies, evaluate risk, monitor "
    "changing market conditions and communicate with other "
    "users. The platform focuses on supporting better trading "
    "decisions rather than simply displaying price charts or "
    "historical backtest results."
)


# ============================================================
# 4.4 MARKETPULSE PURPOSE SUMMARY
# ============================================================

HOME_PURPOSE_SUMMARY = (
    "Research • Test • Analyse • Manage Risk • Communicate"
)


# ============================================================
# 4.5 COMPLETE FEATURE GUIDE
# ============================================================

# This information is displayed in the compact About
# MarketPulse block at the bottom of the Home page.

HOME_FEATURE_GUIDE = [


    # --------------------------------------------------------
    # DASHBOARD
    # --------------------------------------------------------

    {

        "name":
            "Dashboard",

        "description":
            (
                "Central workspace for strategies, backtests, "
                "live market information, monitoring and "
                "user alerts."
            ),

    },


    # --------------------------------------------------------
    # DATA
    # --------------------------------------------------------

    {

        "name":
            "Data",

        "description":
            (
                "Uses Alpaca market data to explore assets, "
                "historical OHLCV prices, charts and changing "
                "market conditions."
            ),

    },


    # --------------------------------------------------------
    # STRATEGIES
    # --------------------------------------------------------

    {

        "name":
            "Strategies",

        "description":
            (
                "Build, backtest and compare trading strategies "
                "while checking robustness and possible "
                "overfitting."
            ),

    },


    # --------------------------------------------------------
    # RISK
    # --------------------------------------------------------

    {

        "name":
            "Risk",

        "description":
            (
                "Supports trade planning through position "
                "sizing, stop-loss analysis and reward-to-risk "
                "calculations."
            ),

    },


    # --------------------------------------------------------
    # COMMUNITY
    # --------------------------------------------------------

    {

        "name":
            "Community",

        "description":
            (
                "Share market updates, trading warnings, risk "
                "alerts, observations, ideas and discussions "
                "with other MarketPulse users."
            ),

    },


    # --------------------------------------------------------
    # INBOX
    # --------------------------------------------------------

    {

        "name":
            "Inbox",

        "description":
            (
                "Private user-to-user messaging with received "
                "messages, sent messages and unread-message "
                "tracking."
            ),

    },


    # --------------------------------------------------------
    # PROFILE
    # --------------------------------------------------------

    {

        "name":
            "Profile",

        "description":
            (
                "Manage personal account information, trading "
                "preferences and individual risk settings."
            ),

    },


    # --------------------------------------------------------
    # ACCOUNT SECURITY
    # --------------------------------------------------------

    {

        "name":
            "Account Security",

        "description":
            (
                "Supports secure authentication, password "
                "changes and email-based password recovery "
                "through Django authentication and Mailjet."
            ),

    },

]


# ============================================================
# 4.6 EDUCATIONAL NOTICE
# ============================================================

HOME_EDUCATIONAL_NOTICE = (
    "MarketPulse is an educational and decision-support "
    "application. Market information, backtesting results, "
    "strategy analysis, community posts and private messages "
    "should not be interpreted as personalised financial or "
    "investment advice."
)


# ============================================================
# 5. DASHBOARD CONFIGURATION
# ============================================================

# These benchmark ETFs provide a concise overview of several
# important parts of the US equity market.
#
# They remain useful for:
#
# - market overview cards
# - comparative benchmark analysis
# - default Dashboard context
#
# The professional chart API can separately support arbitrary
# Alpaca equity and ETF symbols.

DASHBOARD_BENCHMARKS = {

    "SPY":
        "S&P 500 ETF",

    "QQQ":
        "Nasdaq-100 ETF",

    "DIA":
        "Dow Jones ETF",

    "IWM":
        "Russell 2000 ETF",

}


# Number of stored PostgreSQL observations initially available
# to the traditional Dashboard context.

DASHBOARD_CHART_LIMIT = 60


# Browser refresh interval for live Alpaca market information.

DASHBOARD_REFRESH_SECONDS = 60


# ============================================================
# 6. HOME PAGE
# ============================================================

def home(
    request,
):
    """
    Render the MarketPulse landing page.

    The Home page combines:

    - MarketPulse purpose
    - Current technology stack
    - Core application features
    - Community activity
    - Inbox preview
    - Complete feature guide
    - Educational notice


    Public visitors can see:

    - platform information
    - feature descriptions
    - recent Community activity


    Authenticated users can additionally see:

    - recent private messages
    - unread private message count


    Actual post creation and private-message management remain
    inside community/views.py.
    """


    # ========================================================
    # 6.1 RECENT COMMUNITY POSTS
    # ========================================================

    # Load only a small number of Community posts because the
    # Home page should provide a preview rather than reproduce
    # the complete Community Feed.
    #
    # select_related("author") retrieves the related user
    # record in the same query and avoids unnecessary database
    # queries while rendering the template.

    recent_posts = (

        CommunityPost.objects

        .select_related(
            "author"
        )

        .order_by(
            "-created_at"
        )[:4]

    )


    # ========================================================
    # 6.2 DEFAULT INBOX VALUES
    # ========================================================

    # Anonymous visitors do not have access to a private Inbox.
    #
    # An empty QuerySet allows the Home template to safely loop
    # through recent_messages regardless of authentication.

    recent_messages = (
        PrivateMessage.objects.none()
    )


    unread_messages = 0


    # ========================================================
    # 6.3 AUTHENTICATED USER INBOX
    # ========================================================

    if request.user.is_authenticated:


        # ----------------------------------------------------
        # RECENT RECEIVED MESSAGES
        # ----------------------------------------------------

        # Only messages belonging to the currently authenticated
        # recipient are returned.
        #
        # This is essential because one user must never be able
        # to view another user's private Inbox.

        recent_messages = (

            PrivateMessage.objects

            .filter(
                recipient=request.user
            )

            .select_related(
                "sender"
            )

            .order_by(
                "-created_at"
            )[:4]

        )


        # ----------------------------------------------------
        # UNREAD MESSAGE COUNT
        # ----------------------------------------------------

        unread_messages = (

            PrivateMessage.objects

            .filter(
                recipient=request.user,
                is_read=False,
            )

            .count()

        )


    # ========================================================
    # 6.4 HOME PAGE CONTEXT
    # ========================================================

    context = {


        # ----------------------------------------------------
        # CURRENT MARKETPULSE TECHNOLOGY
        # ----------------------------------------------------

        "home_technology_stack":
            HOME_TECHNOLOGY_STACK,


        # ----------------------------------------------------
        # CORE APPLICATION FEATURES
        # ----------------------------------------------------

        "home_core_features":
            HOME_CORE_FEATURES,


        # ----------------------------------------------------
        # ABOUT MARKETPULSE
        # ----------------------------------------------------

        "home_about_description":
            HOME_ABOUT_DESCRIPTION,

        "home_purpose_summary":
            HOME_PURPOSE_SUMMARY,


        # ----------------------------------------------------
        # COMPLETE FEATURE GUIDE
        # ----------------------------------------------------

        "home_feature_guide":
            HOME_FEATURE_GUIDE,


        # ----------------------------------------------------
        # EDUCATIONAL NOTICE
        # ----------------------------------------------------

        "home_educational_notice":
            HOME_EDUCATIONAL_NOTICE,


        # ----------------------------------------------------
        # COMMUNITY
        # ----------------------------------------------------

        "recent_posts":
            recent_posts,


        # ----------------------------------------------------
        # PRIVATE MESSAGING
        # ----------------------------------------------------

        "recent_messages":
            recent_messages,

        "unread_messages":
            unread_messages,


        # Alternative descriptive name is also provided so
        # templates or future components can use either name.

        "unread_message_count":
            unread_messages,

    }


    # ========================================================
    # 6.5 RENDER HOME PAGE
    # ========================================================

    return render(
        request,
        "home.html",
        context,
    )


# ============================================================
# 7. SELECT DASHBOARD MARKET SYMBOL
# ============================================================

def _get_selected_dashboard_symbol(
    request,
):
    """
    Read the selected Dashboard benchmark from the URL.

    Examples:

        /dashboard/?symbol=SPY

        /dashboard/?symbol=QQQ


    This helper controls the traditional benchmark context used
    by the Django-rendered Dashboard.

    The interactive stock-search workspace can load arbitrary
    symbols independently through JavaScript and the Alpaca API.
    """

    symbol = (
        request.GET
        .get(
            "symbol",
            "SPY",
        )
        .strip()
        .upper()
    )


    if (
        symbol
        not in
        DASHBOARD_BENCHMARKS
    ):

        symbol = (
            "SPY"
        )


    return symbol


# ============================================================
# 8. AVAILABLE HISTORICAL CHART SYMBOLS
# ============================================================

def _get_available_chart_symbols():
    """
    Return benchmark symbols that already have historical
    MarketData observations stored in PostgreSQL.

    This information remains useful for:

    - fallback historical charts
    - data-health information
    - strategy testing
    - Market Condition analysis

    Live Alpaca graph availability is handled separately by the
    API layer.
    """

    stored_symbols = set(

        MarketData.objects

        .filter(
            symbol__in=list(
                DASHBOARD_BENCHMARKS.keys()
            )
        )

        .values_list(
            "symbol",
            flat=True,
        )

        .distinct()

    )


    return [

        symbol

        for symbol
        in DASHBOARD_BENCHMARKS

        if symbol in stored_symbols

    ]


# ============================================================
# 9. HISTORICAL POSTGRESQL CHART DATA
# ============================================================

def _get_dashboard_chart_rows(
    symbol,
    limit=DASHBOARD_CHART_LIMIT,
):
    """
    Retrieve stored historical OHLCV observations from the
    MarketData table.

    MarketData records are selected newest-first so the most
    recent observations can be limited efficiently.

    They are then reversed because charting libraries normally
    expect chronological ordering:

        oldest
            ↓
        newest
    """

    rows = list(

        MarketData.objects

        .filter(
            symbol=symbol
        )

        .order_by(
            "-date"
        )[:limit]

    )


    rows.reverse()


    # --------------------------------------------------------
    # Convert Decimal and Date objects into browser-friendly
    # Python values.
    # --------------------------------------------------------

    return [

        {

            "date":
                row.date.isoformat(),

            "open_price":
                float(
                    row.open_price
                ),

            "high_price":
                float(
                    row.high_price
                ),

            "low_price":
                float(
                    row.low_price
                ),

            "close_price":
                float(
                    row.close_price
                ),

            "volume":
                row.volume,

        }

        for row
        in rows

    ]


# ============================================================
# 10. LATEST MARKET CONDITION
# ============================================================

def _get_latest_market_condition(
    symbol,
):
    """
    Retrieve the newest stored Market Condition analysis for the
    selected Dashboard benchmark.

    MarketRegime belongs to the internal analytics layer.

    The Dashboard surfaces only the most recent result so the
    user receives useful market context without exposing a
    separate Analysis application.
    """

    regime = (

        MarketRegime.objects

        .filter(
            symbol=symbol
        )

        .order_by(
            "-date",
            "-created_at",
        )

        .first()

    )


    if regime is None:

        return None


    # --------------------------------------------------------
    # REGIME DISPLAY NAME
    # --------------------------------------------------------

    try:

        display_name = (
            regime.get_regime_display()
        )


    except AttributeError:

        display_name = (
            regime.regime
        )


    return {

        "id":
            regime.pk,

        "symbol":
            regime.symbol,

        "date":
            regime.date,

        "regime":
            regime.regime,

        "display":
            display_name,

        "confidence":
            (
                float(
                    regime.confidence
                )

                if regime.confidence is not None

                else None
            ),

        "volatility":
            (
                float(
                    regime.volatility
                )

                if regime.volatility is not None

                else None
            ),

        "trend_strength":
            (
                float(
                    regime.trend_strength
                )

                if regime.trend_strength is not None

                else None
            ),

    }


# ============================================================
# 11. MARKET DATA HEALTH
# ============================================================

def _get_market_data_health():
    """
    Summarise the historical MarketData currently stored in
    PostgreSQL.

    This provides the Dashboard with information about:

    - total observations
    - number of stored symbols
    - earliest historical observation
    - latest historical observation
    - approximate data staleness
    """

    # --------------------------------------------------------
    # TOTAL OHLCV ROWS
    # --------------------------------------------------------

    total_rows = (
        MarketData.objects
        .count()
    )


    # --------------------------------------------------------
    # DISTINCT SYMBOL COUNT
    # --------------------------------------------------------

    stored_symbol_count = (

        MarketData.objects

        .values(
            "symbol"
        )

        .distinct()

        .count()

    )


    # --------------------------------------------------------
    # LATEST STORED OBSERVATION
    # --------------------------------------------------------

    latest_date = (

        MarketData.objects

        .order_by(
            "-date"
        )

        .values_list(
            "date",
            flat=True,
        )

        .first()

    )


    # --------------------------------------------------------
    # EARLIEST STORED OBSERVATION
    # --------------------------------------------------------

    earliest_date = (

        MarketData.objects

        .order_by(
            "date"
        )

        .values_list(
            "date",
            flat=True,
        )

        .first()

    )


    # --------------------------------------------------------
    # STALENESS
    # --------------------------------------------------------

    days_since_latest = None


    if latest_date:

        days_since_latest = (

            timezone.localdate()
            -
            latest_date

        ).days


    return {

        "total_rows":
            total_rows,

        "stored_symbols":
            stored_symbol_count,

        "earliest_date":
            earliest_date,

        "latest_date":
            latest_date,

        "days_since_latest":
            days_since_latest,

    }


# ============================================================
# 12. ALERT CHOICE HELPERS
# ============================================================

def _get_alert_type_choices():
    """
    Read Alert alert_type choices directly from Django's model
    field metadata.

    This avoids depending on a particular Python constant such
    as:

        Alert.ALERT_TYPES

    because the current model defines its configured choices
    through the field.
    """

    return (

        Alert._meta

        .get_field(
            "alert_type"
        )

        .choices

    )


# ============================================================

def _get_alert_severity_choices():
    """
    Read severity choices directly from the Alert model field.

    The Edit Alert interface can therefore remain aligned with
    the actual model configuration.
    """

    return (

        Alert._meta

        .get_field(
            "severity"
        )

        .choices

    )


# ============================================================
# 13. DASHBOARD
# ============================================================

@login_required
def dashboard(
    request,
):
    """
    Render the authenticated MarketPulse Dashboard.

    Framework mapping:

    Browser
        ↓
    dashboard()
        ↓
    Django ORM
        ↓
    PostgreSQL
        ↓
    dashboard.html
        ↓
    JavaScript
        ↓
    MarketPulse REST API
        ↓
    Alpaca


    The page combines:

    - user strategies
    - backtests
    - historical PostgreSQL data
    - Market Condition analysis
    - generated Alerts
    - configurable AlertRules
    - Alpaca live market information
    """


    # ========================================================
    # 13.1 USER STRATEGIES
    # ========================================================

    strategies = (

        Strategy.objects

        .filter(
            user=request.user
        )

        .order_by(
            "-created_at"
        )

    )


    active_strategies = (

        strategies

        .filter(
            is_active=True
        )

    )


    # ========================================================
    # 13.2 USER BACKTESTS
    # ========================================================

    backtests = (

        Backtest.objects

        .filter(
            strategy__user=request.user
        )

        .select_related(
            "strategy"
        )

        .order_by(
            "-created_at"
        )

    )


    latest_backtest = (
        backtests.first()
    )


    # ========================================================
    # 13.3 AVERAGE WIN RATE
    # ========================================================

    average_win_rate = (

        backtests

        .aggregate(
            value=Avg(
                "win_rate"
            )
        )

        .get(
            "value"
        )

        or
        0

    )


    average_win_rate_pct = (

        float(
            average_win_rate
        )

        *
        100

    )


    # ========================================================
    # 13.4 GENERATED USER ALERTS
    # ========================================================

    alerts = (

        Alert.objects

        .filter(
            user=request.user
        )

        .order_by(
            "-is_active",
            "-created_at",
        )

    )


    active_alerts = (

        alerts

        .filter(
            is_active=True
        )

    )


    unread_alerts = (

        alerts

        .filter(
            is_read=False
        )

    )


    # ========================================================
    # 13.5 CONFIGURABLE ALERT RULES
    # ========================================================

    alert_rules = (

        AlertRule.objects

        .filter(
            user=request.user
        )

        .order_by(
            "-is_enabled",
            "symbol",
            "metric",
            "-created_at",
        )

    )


    enabled_alert_rules = (

        alert_rules

        .filter(
            is_enabled=True
        )

    )


    alert_rule_form = (
        AlertRuleForm()
    )


    # ========================================================
    # 13.6 GENERATED ALERT FORM OPTIONS
    # ========================================================

    alert_type_choices = (
        _get_alert_type_choices()
    )


    alert_severity_choices = (
        _get_alert_severity_choices()
    )


    # ========================================================
    # 13.7 SELECT DEFAULT MARKET BENCHMARK
    # ========================================================

    selected_symbol = (

        _get_selected_dashboard_symbol(
            request
        )

    )


    # ========================================================
    # 13.8 STORED POSTGRESQL HISTORICAL GRAPH DATA
    # ========================================================

    chart_rows = (

        _get_dashboard_chart_rows(
            selected_symbol
        )

    )


    available_chart_symbols = (
        _get_available_chart_symbols()
    )


    # ========================================================
    # 13.9 MARKET CONDITION
    # ========================================================

    market_condition = (

        _get_latest_market_condition(
            selected_symbol
        )

    )


    # ========================================================
    # 13.10 DATA HEALTH
    # ========================================================

    data_health = (
        _get_market_data_health()
    )


    # ========================================================
    # 13.11 DASHBOARD CONTEXT
    # ========================================================

    context = {


        # ----------------------------------------------------
        # USER / STRATEGY STATISTICS
        # ----------------------------------------------------

        "active_strategy_count":
            active_strategies.count(),

        "strategy_count":
            strategies.count(),

        "backtest_count":
            backtests.count(),

        "avg_win_rate":
            average_win_rate_pct,

        "market_data_count":
            data_health[
                "total_rows"
            ],


        # ----------------------------------------------------
        # STRATEGIES / BACKTESTS
        # ----------------------------------------------------

        "strategies":
            strategies,

        "latest_backtest":
            latest_backtest,

        "recent_backtests":
            backtests[:5],


        # ----------------------------------------------------
        # GENERATED ALERT MANAGEMENT
        # ----------------------------------------------------

        "alerts":
            alerts,

        "active_alerts":
            active_alerts,

        "active_alert_count":
            active_alerts.count(),

        "unread_alert_count":
            unread_alerts.count(),

        "alert_type_choices":
            alert_type_choices,

        "alert_severity_choices":
            alert_severity_choices,


        # ----------------------------------------------------
        # CONFIGURABLE ALERT RULES
        # ----------------------------------------------------

        "alert_rules":
            alert_rules,

        "alert_rule_count":
            alert_rules.count(),

        "enabled_alert_rules":
            enabled_alert_rules,

        "enabled_alert_rule_count":
            enabled_alert_rules.count(),

        "alert_rule_form":
            alert_rule_form,


        # ----------------------------------------------------
        # MARKET OVERVIEW
        # ----------------------------------------------------

        "dashboard_benchmarks":
            DASHBOARD_BENCHMARKS,

        "selected_symbol":
            selected_symbol,

        "available_chart_symbols":
            available_chart_symbols,

        "market_chart_rows":
            chart_rows,

        "market_chart_has_data":
            bool(
                chart_rows
            ),

        "market_condition":
            market_condition,


        # ----------------------------------------------------
        # DATA HEALTH
        # ----------------------------------------------------

        "data_health":
            data_health,


        # ----------------------------------------------------
        # AUTOMATIC ALPACA REFRESH
        # ----------------------------------------------------

        "dashboard_refresh_seconds":
            DASHBOARD_REFRESH_SECONDS,

    }


    # ========================================================
    # 13.12 RENDER DASHBOARD
    # ========================================================

    return render(
        request,
        "dashboard.html",
        context,
    )


# ============================================================
# 14. EDIT GENERATED ALERT
# ============================================================

@login_required
@require_POST
def edit_alert(
    request,
    alert_id,
):
    """
    Update an Alert notification belonging to the authenticated
    user.

    IMPORTANT:

    This edits the generated notification itself.

    It does NOT alter an AlertRule monitoring condition.


    Security:

        user=request.user

    prevents a user from editing another user's alert simply by
    changing the numeric identifier in the URL.
    """

    alert = get_object_or_404(
        Alert,
        pk=alert_id,
        user=request.user,
    )


    form = AlertEditForm(
        request.POST,
        instance=alert,
    )


    if form.is_valid():

        updated_alert = (
            form.save()
        )


        messages.success(
            request,
            (
                f'Alert "{updated_alert.title}" '
                f"was updated successfully."
            ),
        )


    else:

        messages.error(
            request,
            (
                "The alert could not be updated. "
                "Please check the submitted values."
            ),
        )


    return redirect(
        "dashboard"
    )


# ============================================================
# 15. MARK GENERATED ALERT AS READ
# ============================================================

@login_required
@require_POST
def mark_alert_read(
    request,
    alert_id,
):
    """
    Acknowledge a generated Alert notification.
    """

    alert = get_object_or_404(
        Alert,
        pk=alert_id,
        user=request.user,
    )


    alert.mark_as_read()


    messages.success(
        request,
        f'Alert "{alert.title}" was marked as read.',
    )


    return redirect(
        "dashboard"
    )


# ============================================================
# 16. TOGGLE GENERATED ALERT RESOLUTION
# ============================================================

@login_required
@require_POST
def toggle_alert_resolution(
    request,
    alert_id,
):
    """
    Resolve an active generated Alert or reopen a previously
    resolved Alert.
    """

    alert = get_object_or_404(
        Alert,
        pk=alert_id,
        user=request.user,
    )


    if alert.is_active:

        alert.resolve()


        messages.success(
            request,
            f'Alert "{alert.title}" was resolved.',
        )


    else:

        alert.reopen()


        messages.info(
            request,
            f'Alert "{alert.title}" was reopened.',
        )


    return redirect(
        "dashboard"
    )


# ============================================================
# 17. CREATE ALERT RULE
# ============================================================

@login_required
@require_POST
def create_alert_rule(
    request,
):
    """
    Create a configurable market-monitoring rule.
    """

    form = (
        AlertRuleForm(
            request.POST
        )
    )


    if form.is_valid():

        alert_rule = (
            form.save(
                commit=False
            )
        )


        alert_rule.user = (
            request.user
        )


        alert_rule.save()


        messages.success(
            request,
            (
                f'Alert rule for "{alert_rule.symbol}" '
                f"was created successfully."
            ),
        )


    else:

        messages.error(
            request,
            (
                "The alert rule could not be created. "
                "Please check the submitted values."
            ),
        )


    return redirect(
        "dashboard"
    )


# ============================================================
# 18. EDIT ALERT RULE
# ============================================================

@login_required
@require_POST
def edit_alert_rule(
    request,
    rule_id,
):
    """
    Modify an existing AlertRule owned by the current user.
    """

    alert_rule = (
        get_object_or_404(
            AlertRule,
            pk=rule_id,
            user=request.user,
        )
    )


    form = (
        AlertRuleForm(
            request.POST,
            instance=alert_rule,
        )
    )


    if form.is_valid():

        updated_rule = (
            form.save()
        )


        messages.success(
            request,
            (
                f'Alert rule for "{updated_rule.symbol}" '
                f"was updated successfully."
            ),
        )


    else:

        messages.error(
            request,
            (
                "The alert rule could not be updated. "
                "Please check the submitted values."
            ),
        )


    return redirect(
        "dashboard"
    )


# ============================================================
# 19. ENABLE / DISABLE ALERT RULE
# ============================================================

@login_required
@require_POST
def toggle_alert_rule(
    request,
    rule_id,
):
    """
    Toggle whether MarketPulse should actively evaluate an
    AlertRule.
    """

    alert_rule = (
        get_object_or_404(
            AlertRule,
            pk=rule_id,
            user=request.user,
        )
    )


    alert_rule.is_enabled = (
        not
        alert_rule.is_enabled
    )


    alert_rule.save(
        update_fields=[
            "is_enabled",
            "updated_at",
        ]
    )


    state = (

        "enabled"

        if alert_rule.is_enabled

        else "disabled"

    )


    messages.info(
        request,
        (
            f'{alert_rule.symbol} alert rule '
            f"was {state}."
        ),
    )


    return redirect(
        "dashboard"
    )


# ============================================================
# 20. DELETE ALERT RULE
# ============================================================

@login_required
@require_POST
def delete_alert_rule(
    request,
    rule_id,
):
    """
    Permanently delete a monitoring AlertRule.

    Existing generated Alert records are intentionally
    preserved.
    """

    alert_rule = (
        get_object_or_404(
            AlertRule,
            pk=rule_id,
            user=request.user,
        )
    )


    symbol = (
        alert_rule.symbol
    )


    condition = (
        alert_rule.condition_display
    )


    alert_rule.delete()


    messages.success(
        request,
        (
            f"{symbol} alert rule "
            f"({condition}) was deleted."
        ),
    )


    return redirect(
        "dashboard"
    )