"""
============================================================
MARKETPULSE - CORE HOME / DASHBOARD VIEWS
============================================================

Framework mapping:

Browser
    ↓
marketpulse/urls.py
    ↓
core/views.py
    ↓
Django Forms / Django ORM
    ↓
PostgreSQL / Neon
    ↓
templates/dashboard.html


DASHBOARD PURPOSE:

The Dashboard is the user's high-level MarketPulse control
centre.

It summarises:

1. User strategies
2. Backtest activity
3. Average strategy win rate
4. Historical market-data storage
5. Current selected market benchmark
6. Stored historical chart data
7. Latest Market Condition
8. Persistent generated alerts
9. Configurable user alert rules
10. Unread alert count
11. Recent backtest activity


ALERT ARCHITECTURE:

AlertRule
    ↓
Defines what MarketPulse should monitor

Example:

    SPY
    Price
    Greater Than
    800


Alert
    ↓
Represents an actual notification/event generated by
MarketPulse.

Example:

    "SPY moved above $800"


This distinction allows users to edit monitoring conditions
without rewriting historical alert records.


LIVE MARKET DATA:

Current / recent Alpaca information is fetched through:

    /api/dashboard/market-overview/

The interactive professional chart can also request arbitrary
symbols through the Alpaca API endpoints.

The normal Django Dashboard view supplies PostgreSQL and user
information immediately so the page remains useful before
JavaScript finishes loading live market information.

============================================================
"""


# ============================================================
# 1. DJANGO IMPORTS
# ============================================================

from django.contrib import messages

from django.contrib.auth.decorators import login_required

from django.db.models import Avg

from django.shortcuts import (
    get_object_or_404,
    redirect,
    render,
)

from django.utils import timezone

from django.views.decorators.http import require_POST


# ============================================================
# 2. INTERNAL ANALYTICS
# ============================================================

# analysis_tools remains an internal analytical layer.
#
# Market Condition results are surfaced on the Dashboard and
# within the Data workflow rather than requiring a separate
# public Analysis navigation tab.

from analysis_tools.models import (
    MarketRegime,
)


# ============================================================
# 3. CORE MODELS
# ============================================================

from .models import (
    Alert,
    AlertRule,
    Backtest,
    MarketData,
    Strategy,
)


# ============================================================
# 3.1 CORE FORMS
# ============================================================

# AlertEditForm:
#
#     Edits an already-generated Alert record.
#
# AlertRuleForm:
#
#     Creates or modifies a monitoring condition configured
#     by the user.

from .forms import (
    AlertEditForm,
    AlertRuleForm,
)


# ============================================================
# 4. DASHBOARD CONFIGURATION
# ============================================================

# These benchmark ETFs provide a concise overview of several
# important parts of the US equity market.
#
# They remain useful for:
#
# - market overview cards
# - comparative benchmark analysis
# - default Dashboard context
#
# The professional chart API can separately support arbitrary
# Alpaca equity and ETF symbols.

DASHBOARD_BENCHMARKS = {

    "SPY":
        "S&P 500 ETF",

    "QQQ":
        "Nasdaq-100 ETF",

    "DIA":
        "Dow Jones ETF",

    "IWM":
        "Russell 2000 ETF",

}


# Number of stored PostgreSQL observations initially available
# to the traditional Dashboard context.
DASHBOARD_CHART_LIMIT = 60


# Browser refresh interval for live Alpaca market information.
DASHBOARD_REFRESH_SECONDS = 60


# ============================================================
# 5. HOME PAGE
# ============================================================

def home(
    request,
):
    """
    Render the public MarketPulse landing page.
    """

    return render(
        request,
        "home.html",
    )


# ============================================================
# 6. SELECT DASHBOARD MARKET SYMBOL
# ============================================================

def _get_selected_dashboard_symbol(
    request,
):
    """
    Read the selected Dashboard benchmark from the URL.

    Examples:

        /dashboard/?symbol=SPY

        /dashboard/?symbol=QQQ


    This helper controls the traditional benchmark context used
    by the Django-rendered Dashboard.

    The future interactive stock-search workspace can load
    arbitrary symbols independently through JavaScript and the
    Alpaca API.
    """

    symbol = (
        request.GET
        .get(
            "symbol",
            "SPY",
        )
        .strip()
        .upper()
    )


    if (
        symbol
        not in
        DASHBOARD_BENCHMARKS
    ):

        symbol = (
            "SPY"
        )


    return symbol


# ============================================================
# 7. AVAILABLE HISTORICAL CHART SYMBOLS
# ============================================================

def _get_available_chart_symbols():
    """
    Return benchmark symbols that already have historical
    MarketData observations stored in PostgreSQL.

    This information remains useful for:

    - fallback historical charts
    - data-health information
    - strategy testing
    - Market Condition analysis

    Live Alpaca graph availability is handled separately by the
    API layer.
    """

    stored_symbols = set(

        MarketData.objects

        .filter(
            symbol__in=list(
                DASHBOARD_BENCHMARKS.keys()
            )
        )

        .values_list(
            "symbol",
            flat=True,
        )

        .distinct()

    )


    return [

        symbol

        for symbol
        in DASHBOARD_BENCHMARKS

        if symbol in stored_symbols

    ]


# ============================================================
# 8. HISTORICAL POSTGRESQL CHART DATA
# ============================================================

def _get_dashboard_chart_rows(
    symbol,
    limit=DASHBOARD_CHART_LIMIT,
):
    """
    Retrieve stored historical OHLCV observations from the
    MarketData table.

    MarketData records are selected newest-first so the most
    recent observations can be limited efficiently.

    They are then reversed because charting libraries normally
    expect chronological ordering:

        oldest
            ↓
        newest
    """

    rows = list(

        MarketData.objects

        .filter(
            symbol=symbol
        )

        .order_by(
            "-date"
        )[:limit]

    )


    rows.reverse()


    # --------------------------------------------------------
    # Convert Decimal and Date objects into browser-friendly
    # Python values.
    # --------------------------------------------------------

    return [

        {

            "date":
                row.date.isoformat(),

            "open_price":
                float(
                    row.open_price
                ),

            "high_price":
                float(
                    row.high_price
                ),

            "low_price":
                float(
                    row.low_price
                ),

            "close_price":
                float(
                    row.close_price
                ),

            "volume":
                row.volume,

        }

        for row
        in rows

    ]


# ============================================================
# 9. LATEST MARKET CONDITION
# ============================================================

def _get_latest_market_condition(
    symbol,
):
    """
    Retrieve the newest stored Market Condition analysis for the
    selected Dashboard benchmark.

    MarketRegime belongs to the internal analytics layer.

    The Dashboard surfaces only the most recent result so the
    user receives useful market context without exposing a
    separate Analysis application.
    """

    regime = (

        MarketRegime.objects

        .filter(
            symbol=symbol
        )

        .order_by(
            "-date",
            "-created_at",
        )

        .first()

    )


    if regime is None:

        return None


    # --------------------------------------------------------
    # REGIME DISPLAY NAME
    # --------------------------------------------------------

    try:

        display_name = (
            regime.get_regime_display()
        )


    except AttributeError:

        display_name = (
            regime.regime
        )


    return {

        "id":
            regime.pk,

        "symbol":
            regime.symbol,

        "date":
            regime.date,

        "regime":
            regime.regime,

        "display":
            display_name,

        "confidence":
            (
                float(
                    regime.confidence
                )

                if regime.confidence is not None

                else None
            ),

        "volatility":
            (
                float(
                    regime.volatility
                )

                if regime.volatility is not None

                else None
            ),

        "trend_strength":
            (
                float(
                    regime.trend_strength
                )

                if regime.trend_strength is not None

                else None
            ),

    }


# ============================================================
# 10. MARKET DATA HEALTH
# ============================================================

def _get_market_data_health():
    """
    Summarise the historical MarketData currently stored in
    PostgreSQL.

    This provides the Dashboard with information about:

    - total observations
    - number of stored symbols
    - earliest historical observation
    - latest historical observation
    - approximate data staleness
    """

    # --------------------------------------------------------
    # TOTAL OHLCV ROWS
    # --------------------------------------------------------

    total_rows = (
        MarketData.objects
        .count()
    )


    # --------------------------------------------------------
    # DISTINCT SYMBOL COUNT
    # --------------------------------------------------------

    stored_symbol_count = (

        MarketData.objects

        .values(
            "symbol"
        )

        .distinct()

        .count()

    )


    # --------------------------------------------------------
    # LATEST STORED OBSERVATION
    # --------------------------------------------------------

    latest_date = (

        MarketData.objects

        .order_by(
            "-date"
        )

        .values_list(
            "date",
            flat=True,
        )

        .first()

    )


    # --------------------------------------------------------
    # EARLIEST STORED OBSERVATION
    # --------------------------------------------------------

    earliest_date = (

        MarketData.objects

        .order_by(
            "date"
        )

        .values_list(
            "date",
            flat=True,
        )

        .first()

    )


    # --------------------------------------------------------
    # STALENESS
    # --------------------------------------------------------

    days_since_latest = None


    if latest_date:

        days_since_latest = (

            timezone.localdate()
            -
            latest_date

        ).days


    return {

        "total_rows":
            total_rows,

        "stored_symbols":
            stored_symbol_count,

        "earliest_date":
            earliest_date,

        "latest_date":
            latest_date,

        "days_since_latest":
            days_since_latest,

    }


# ============================================================
# 11. ALERT CHOICE HELPERS
# ============================================================

def _get_alert_type_choices():
    """
    Read Alert alert_type choices directly from Django's model
    field metadata.

    This avoids depending on a particular Python constant such
    as:

        Alert.ALERT_TYPES

    because the current model defines its own configured choices
    through the field.
    """

    return (

        Alert._meta

        .get_field(
            "alert_type"
        )

        .choices

    )


# ============================================================

def _get_alert_severity_choices():
    """
    Read severity choices directly from the Alert model field.

    The Edit Alert interface can therefore remain aligned with
    the actual model configuration.
    """

    return (

        Alert._meta

        .get_field(
            "severity"
        )

        .choices

    )


# ============================================================
# 12. DASHBOARD
# ============================================================

@login_required
def dashboard(
    request,
):
    """
    Render the authenticated MarketPulse Dashboard.

    Framework mapping:

    Browser
        ↓
    dashboard()
        ↓
    Django ORM
        ↓
    PostgreSQL
        ↓
    dashboard.html
        ↓
    JavaScript
        ↓
    MarketPulse REST API
        ↓
    Alpaca


    The page combines:

    - user strategies
    - backtests
    - historical PostgreSQL data
    - Market Condition analysis
    - generated Alerts
    - configurable AlertRules
    - Alpaca live market information
    """


    # ========================================================
    # 12.1 USER STRATEGIES
    # ========================================================

    strategies = (

        Strategy.objects

        .filter(
            user=request.user
        )

        .order_by(
            "-created_at"
        )

    )


    active_strategies = (

        strategies

        .filter(
            is_active=True
        )

    )


    # ========================================================
    # 12.2 USER BACKTESTS
    # ========================================================

    backtests = (

        Backtest.objects

        .filter(
            strategy__user=request.user
        )

        .select_related(
            "strategy"
        )

        .order_by(
            "-created_at"
        )

    )


    latest_backtest = (
        backtests.first()
    )


    # ========================================================
    # 12.3 AVERAGE WIN RATE
    # ========================================================

    average_win_rate = (

        backtests

        .aggregate(
            value=Avg(
                "win_rate"
            )
        )

        .get(
            "value"
        )

        or
        0

    )


    # Backtest.win_rate is stored as a decimal ratio.
    #
    # Example:
    #
    #     0.58
    #
    # becomes:
    #
    #     58%

    average_win_rate_pct = (

        float(
            average_win_rate
        )

        *
        100

    )


    # ========================================================
    # 12.4 GENERATED USER ALERTS
    # ========================================================

    # Alert represents an event or notification already created
    # by MarketPulse.
    #
    # These are intentionally separate from AlertRule.

    alerts = (

        Alert.objects

        .filter(
            user=request.user
        )

        .order_by(
            "-is_active",
            "-created_at",
        )

    )


    # --------------------------------------------------------
    # ACTIVE GENERATED ALERTS
    # --------------------------------------------------------

    active_alerts = (

        alerts

        .filter(
            is_active=True
        )

    )


    # --------------------------------------------------------
    # UNREAD GENERATED ALERTS
    # --------------------------------------------------------

    unread_alerts = (

        alerts

        .filter(
            is_read=False
        )

    )


    # ========================================================
    # 12.5 CONFIGURABLE ALERT RULES
    # ========================================================

    # AlertRule represents what the user wants MarketPulse to
    # monitor.
    #
    # Example:
    #
    #     AAPL
    #     Price
    #     >
    #     260
    #
    # The rules will appear underneath the professional chart
    # and can be created, edited, enabled/disabled or deleted.

    alert_rules = (

        AlertRule.objects

        .filter(
            user=request.user
        )

        .order_by(
            "-is_enabled",
            "symbol",
            "metric",
            "-created_at",
        )

    )


    # --------------------------------------------------------
    # ENABLED RULES
    # --------------------------------------------------------

    enabled_alert_rules = (

        alert_rules

        .filter(
            is_enabled=True
        )

    )


    # --------------------------------------------------------
    # BLANK CREATE RULE FORM
    # --------------------------------------------------------

    alert_rule_form = (
        AlertRuleForm()
    )


    # ========================================================
    # 12.6 GENERATED ALERT FORM OPTIONS
    # ========================================================

    # Read directly from model metadata rather than depending
    # on hard-coded constants.

    alert_type_choices = (
        _get_alert_type_choices()
    )


    alert_severity_choices = (
        _get_alert_severity_choices()
    )


    # ========================================================
    # 12.7 SELECT DEFAULT MARKET BENCHMARK
    # ========================================================

    selected_symbol = (

        _get_selected_dashboard_symbol(
            request
        )

    )


    # ========================================================
    # 12.8 STORED POSTGRESQL HISTORICAL GRAPH DATA
    # ========================================================

    # This remains available for:
    #
    # - fallback rendering
    # - data-health information
    # - analytics
    #
    # The new interactive trading chart will primarily request
    # current historical data from Alpaca through the API.

    chart_rows = (

        _get_dashboard_chart_rows(
            selected_symbol
        )

    )


    available_chart_symbols = (
        _get_available_chart_symbols()
    )


    # ========================================================
    # 12.9 MARKET CONDITION
    # ========================================================

    market_condition = (

        _get_latest_market_condition(
            selected_symbol
        )

    )


    # ========================================================
    # 12.10 DATA HEALTH
    # ========================================================

    data_health = (
        _get_market_data_health()
    )


    # ========================================================
    # 12.11 DASHBOARD CONTEXT
    # ========================================================

    context = {


        # ----------------------------------------------------
        # USER / STRATEGY STATISTICS
        # ----------------------------------------------------

        "active_strategy_count":
            active_strategies.count(),

        "strategy_count":
            strategies.count(),

        "backtest_count":
            backtests.count(),

        "avg_win_rate":
            average_win_rate_pct,

        "market_data_count":
            data_health[
                "total_rows"
            ],


        # ----------------------------------------------------
        # STRATEGIES / BACKTESTS
        # ----------------------------------------------------

        "strategies":
            strategies,

        "latest_backtest":
            latest_backtest,

        "recent_backtests":
            backtests[:5],


        # ----------------------------------------------------
        # GENERATED ALERT MANAGEMENT
        # ----------------------------------------------------

        "alerts":
            alerts,

        "active_alerts":
            active_alerts,

        "active_alert_count":
            active_alerts.count(),

        "unread_alert_count":
            unread_alerts.count(),

        "alert_type_choices":
            alert_type_choices,

        "alert_severity_choices":
            alert_severity_choices,


        # ----------------------------------------------------
        # CONFIGURABLE ALERT RULES
        # ----------------------------------------------------

        "alert_rules":
            alert_rules,

        "alert_rule_count":
            alert_rules.count(),

        "enabled_alert_rules":
            enabled_alert_rules,

        "enabled_alert_rule_count":
            enabled_alert_rules.count(),

        "alert_rule_form":
            alert_rule_form,


        # ----------------------------------------------------
        # MARKET OVERVIEW
        # ----------------------------------------------------

        "dashboard_benchmarks":
            DASHBOARD_BENCHMARKS,

        "selected_symbol":
            selected_symbol,

        "available_chart_symbols":
            available_chart_symbols,

        "market_chart_rows":
            chart_rows,

        "market_chart_has_data":
            bool(
                chart_rows
            ),

        "market_condition":
            market_condition,


        # ----------------------------------------------------
        # DATA HEALTH
        # ----------------------------------------------------

        "data_health":
            data_health,


        # ----------------------------------------------------
        # AUTOMATIC ALPACA REFRESH
        # ----------------------------------------------------

        "dashboard_refresh_seconds":
            DASHBOARD_REFRESH_SECONDS,

    }


    # ========================================================
    # 12.12 RENDER DASHBOARD
    # ========================================================

    return render(
        request,
        "dashboard.html",
        context,
    )


# ============================================================
# 13. EDIT GENERATED ALERT
# ============================================================

@login_required
@require_POST
def edit_alert(
    request,
    alert_id,
):
    """
    Update an Alert notification belonging to the authenticated
    user.

    IMPORTANT:

    This edits the generated notification itself.

    It does NOT alter an AlertRule monitoring condition.


    Security:

        user=request.user

    prevents a user from editing another user's alert simply by
    changing the numeric identifier in the URL.
    """


    # ========================================================
    # 13.1 FIND CURRENT USER'S ALERT
    # ========================================================

    alert = get_object_or_404(
        Alert,
        pk=alert_id,
        user=request.user,
    )


    # ========================================================
    # 13.2 BIND SUBMITTED VALUES
    # ========================================================

    form = AlertEditForm(
        request.POST,
        instance=alert,
    )


    # ========================================================
    # 13.3 SAVE VALID ALERT
    # ========================================================

    if form.is_valid():

        updated_alert = (
            form.save()
        )


        messages.success(
            request,
            (
                f'Alert "{updated_alert.title}" '
                f"was updated successfully."
            ),
        )


    # ========================================================
    # 13.4 INVALID ALERT FORM
    # ========================================================

    else:

        messages.error(
            request,
            (
                "The alert could not be updated. "
                "Please check the submitted values."
            ),
        )


    # ========================================================
    # 13.5 RETURN TO DASHBOARD
    # ========================================================

    return redirect(
        "dashboard"
    )


# ============================================================
# 14. MARK GENERATED ALERT AS READ
# ============================================================

@login_required
@require_POST
def mark_alert_read(
    request,
    alert_id,
):
    """
    Acknowledge a generated Alert notification.

    Read and resolved intentionally mean different things.

    Read:

        User has seen the alert.

    Resolved:

        The condition represented by the alert no longer needs
        active attention.
    """


    # ========================================================
    # 14.1 FIND USER ALERT
    # ========================================================

    alert = get_object_or_404(
        Alert,
        pk=alert_id,
        user=request.user,
    )


    # ========================================================
    # 14.2 MARK AS READ
    # ========================================================

    alert.mark_as_read()


    # ========================================================
    # 14.3 USER FEEDBACK
    # ========================================================

    messages.success(
        request,
        f'Alert "{alert.title}" was marked as read.',
    )


    # ========================================================
    # 14.4 RETURN TO DASHBOARD
    # ========================================================

    return redirect(
        "dashboard"
    )


# ============================================================
# 15. TOGGLE GENERATED ALERT RESOLUTION
# ============================================================

@login_required
@require_POST
def toggle_alert_resolution(
    request,
    alert_id,
):
    """
    Resolve an active generated Alert or reopen a previously
    resolved Alert.

    Alert records are preserved instead of deleted because they
    provide historical evidence of conditions detected by
    MarketPulse.
    """


    # ========================================================
    # 15.1 FIND USER ALERT
    # ========================================================

    alert = get_object_or_404(
        Alert,
        pk=alert_id,
        user=request.user,
    )


    # ========================================================
    # 15.2 ACTIVE → RESOLVED
    # ========================================================

    if alert.is_active:

        alert.resolve()


        messages.success(
            request,
            f'Alert "{alert.title}" was resolved.',
        )


    # ========================================================
    # 15.3 RESOLVED → ACTIVE
    # ========================================================

    else:

        alert.reopen()


        messages.info(
            request,
            f'Alert "{alert.title}" was reopened.',
        )


    # ========================================================
    # 15.4 RETURN TO DASHBOARD
    # ========================================================

    return redirect(
        "dashboard"
    )


# ============================================================
# 16. CREATE ALERT RULE
# ============================================================

@login_required
@require_POST
def create_alert_rule(
    request,
):
    """
    Create a configurable market-monitoring rule.

    Framework mapping:

    Dashboard
        ↓
    Add Alert
        ↓
    POST
        ↓
    AlertRuleForm
        ↓
    AlertRule
        ↓
    PostgreSQL


    Example:

        Symbol:
            AAPL

        Metric:
            Price

        Operator:
            Greater Than

        Threshold:
            260

        Result:

            MarketPulse can later monitor whether:

                AAPL price > 260
    """


    # ========================================================
    # 16.1 BIND CREATE FORM
    # ========================================================

    form = (
        AlertRuleForm(
            request.POST
        )
    )


    # ========================================================
    # 16.2 VALID RULE
    # ========================================================

    if form.is_valid():

        alert_rule = (
            form.save(
                commit=False
            )
        )


        # ----------------------------------------------------
        # SECURITY:
        #
        # User ownership is assigned server-side.
        #
        # It is intentionally NOT trusted from form input.
        # ----------------------------------------------------

        alert_rule.user = (
            request.user
        )


        alert_rule.save()


        messages.success(
            request,
            (
                f'Alert rule for "{alert_rule.symbol}" '
                f"was created successfully."
            ),
        )


    # ========================================================
    # 16.3 INVALID RULE
    # ========================================================

    else:

        messages.error(
            request,
            (
                "The alert rule could not be created. "
                "Please check the submitted values."
            ),
        )


    # ========================================================
    # 16.4 RETURN TO DASHBOARD
    # ========================================================

    return redirect(
        "dashboard"
    )


# ============================================================
# 17. EDIT ALERT RULE
# ============================================================

@login_required
@require_POST
def edit_alert_rule(
    request,
    rule_id,
):
    """
    Modify an existing AlertRule owned by the current user.

    The ownership constraint prevents one authenticated user
    from changing another user's monitoring rules.
    """


    # ========================================================
    # 17.1 FIND CURRENT USER'S RULE
    # ========================================================

    alert_rule = (
        get_object_or_404(
            AlertRule,
            pk=rule_id,
            user=request.user,
        )
    )


    # ========================================================
    # 17.2 BIND EDIT FORM
    # ========================================================

    form = (
        AlertRuleForm(
            request.POST,
            instance=alert_rule,
        )
    )


    # ========================================================
    # 17.3 SAVE VALID RULE
    # ========================================================

    if form.is_valid():

        updated_rule = (
            form.save()
        )


        messages.success(
            request,
            (
                f'Alert rule for "{updated_rule.symbol}" '
                f"was updated successfully."
            ),
        )


    # ========================================================
    # 17.4 INVALID RULE
    # ========================================================

    else:

        messages.error(
            request,
            (
                "The alert rule could not be updated. "
                "Please check the submitted values."
            ),
        )


    # ========================================================
    # 17.5 RETURN TO DASHBOARD
    # ========================================================

    return redirect(
        "dashboard"
    )


# ============================================================
# 18. ENABLE / DISABLE ALERT RULE
# ============================================================

@login_required
@require_POST
def toggle_alert_rule(
    request,
    rule_id,
):
    """
    Toggle whether MarketPulse should actively evaluate an
    AlertRule.

    Example:

        Enabled
            ↓
        rule can be evaluated

        Disabled
            ↓
        rule remains stored but is ignored
    """


    # ========================================================
    # 18.1 FIND CURRENT USER'S RULE
    # ========================================================

    alert_rule = (
        get_object_or_404(
            AlertRule,
            pk=rule_id,
            user=request.user,
        )
    )


    # ========================================================
    # 18.2 TOGGLE STATE
    # ========================================================

    alert_rule.is_enabled = (
        not
        alert_rule.is_enabled
    )


    # ========================================================
    # 18.3 SAVE STATE
    # ========================================================

    alert_rule.save(
        update_fields=[
            "is_enabled",
            "updated_at",
        ]
    )


    # ========================================================
    # 18.4 BUILD USER MESSAGE
    # ========================================================

    state = (

        "enabled"

        if alert_rule.is_enabled

        else "disabled"

    )


    messages.info(
        request,
        (
            f'{alert_rule.symbol} alert rule '
            f"was {state}."
        ),
    )


    # ========================================================
    # 18.5 RETURN TO DASHBOARD
    # ========================================================

    return redirect(
        "dashboard"
    )


# ============================================================
# 19. DELETE ALERT RULE
# ============================================================

@login_required
@require_POST
def delete_alert_rule(
    request,
    rule_id,
):
    """
    Permanently delete a monitoring AlertRule.

    IMPORTANT:

    Deleting a rule does NOT delete existing generated Alert
    records.

    This preserves historical notification information while
    allowing the user to stop monitoring a condition.
    """


    # ========================================================
    # 19.1 FIND CURRENT USER'S RULE
    # ========================================================

    alert_rule = (
        get_object_or_404(
            AlertRule,
            pk=rule_id,
            user=request.user,
        )
    )


    # Save information before deleting the database object.

    symbol = (
        alert_rule.symbol
    )


    condition = (
        alert_rule.condition_display
    )


    # ========================================================
    # 19.2 DELETE RULE
    # ========================================================

    alert_rule.delete()


    # ========================================================
    # 19.3 USER FEEDBACK
    # ========================================================

    messages.success(
        request,
        (
            f"{symbol} alert rule "
            f"({condition}) was deleted."
        ),
    )


    # ========================================================
    # 19.4 RETURN TO DASHBOARD
    # ========================================================

    return redirect(
        "dashboard"
    )