# Generated by Django 5.2.17 on 2026-08-30 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRegime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('regime', models.CharField(choices=[('bull', 'Bull Market'), ('bear', 'Bear Market'), ('sideways', 'Sideways'), ('volatile', 'High Volatility')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=6, max_digits=8)),
                ('volatility', models.DecimalField(decimal_places=6, max_digits=10)),
                ('trend_strength', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'date'), name='unique_regime_date')],
            },
        ),
        migrations.CreateModel(
            name='OverfittingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20)),
                ('test_period', models.CharField(max_length=60)),
                ('in_sample_return', models.DecimalField(decimal_places=6, max_digits=10)),
                ('out_sample_return', models.DecimalField(decimal_places=6, max_digits=10)),
                ('overfitting_score', models.DecimalField(decimal_places=6, max_digits=10)),
                ('is_overfitted', models.BooleanField(default=False)),
                ('recommendations', models.TextField(blank=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overfitting_tests', to='core.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overfitting_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StressTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20)),
                ('test_type', models.CharField(choices=[('crash', 'Market Crash'), ('volatility_spike', 'Volatility Spike'), ('liquidity_crisis', 'Liquidity Crisis'), ('regime_change', 'Regime Change')], max_length=40)),
                ('test_parameters', models.JSONField(default=dict)),
                ('max_drawdown', models.DecimalField(decimal_places=6, max_digits=10)),
                ('recovery_time', models.PositiveIntegerField(default=0)),
                ('robustness_score', models.DecimalField(decimal_places=6, max_digits=10)),
                ('passed_test', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_tests', to='core.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
