# ============================================================
# ANALYSIS TOOLS - INITIAL DATABASE MIGRATION
# ============================================================
# Generated by Django 5.2.17 on 2026-08-30 09:20
#
# FILE PURPOSE:
# This is the first migration for the analysis_tools Django app.
# It tells Django how to create the database tables required for:
#
# 1. MarketRegime
# 2. OverfittingTest
# 3. StressTest
#
# FRAMEWORK FLOW:
#
# analysis_tools/models.py
#         ↓
# python manage.py makemigrations
#         ↓
# analysis_tools/migrations/0001_initial.py
#         ↓
# Django Migration Framework
#         ↓
# Django SchemaEditor
#         ↓
# PostgreSQL / Database
#
# PROGRAMMING LANGUAGE CONCEPTS USED:
#
# - Imports
# - Modules
# - Classes
# - Inheritance
# - Variables
# - Assignment
# - Lists
# - Tuples
# - Dictionaries
# - Strings
# - Numbers
# - Boolean values
# - Function / constructor calls
# - Keyword arguments
# - Objects
# - Object-Oriented Programming
# - Declarative programming
#
# DJANGO CONCEPTS USED:
#
# - Migration framework
# - Django ORM
# - Models
# - Fields
# - Foreign keys
# - Database constraints
# - Migration dependencies
# - User-model dependency
# - Referential integrity
# ============================================================

# ============================================================
# 1. IMPORT DJANGO MIGRATION REQUIREMENTS
# ============================================================

import django.db.models.deletion  # IMPORT / MODULE: Gives this migration access to Django database deletion behaviour such as CASCADE.
from django.conf import settings  # IMPORT: Gives access to Django project settings, including AUTH_USER_MODEL.
from django.db import migrations, models  # IMPORT: migrations builds database changes; models provides Django database field classes.

# ============================================================
# 2. MIGRATION CLASS
# ============================================================

class Migration(migrations.Migration):  # CLASS + INHERITANCE: Creates this migration by inheriting Django's Migration class.

    # ========================================================
    # 2.1 INITIAL MIGRATION SETTING
    # ========================================================

    initial = True  # VARIABLE + BOOLEAN + ASSIGNMENT: Marks this as the first migration for the analysis_tools app.

    # ========================================================
    # 2.2 MIGRATION DEPENDENCIES
    # ========================================================

    dependencies = [  # VARIABLE + LIST: Stores migrations that must exist before this migration can run.
        ('core', '0001_initial'),  # TUPLE + STRINGS: Requires the core app's first migration before analysis_tools is created.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),  # FUNCTION CALL + ATTRIBUTE ACCESS: Adds a dependency on the project's configured Django user model.
    ]  # LIST: Ends the migration dependency list.

    # ========================================================
    # 2.3 DATABASE OPERATIONS
    # ========================================================

    operations = [  # VARIABLE + LIST: Stores the database operations Django must perform for this migration.

        # ====================================================
        # 3. CREATE MARKET REGIME MODEL
        # ====================================================
        #
        # PURPOSE:
        # Stores the detected market condition for a symbol
        # on a particular date.
        #
        # EXAMPLES OF REGIMES:
        # - Bull Market
        # - Bear Market
        # - Sideways
        # - High Volatility
        #
        # MARKETPULSE FLOW:
        #
        # Market Data
        #     ↓
        # analysis_tools analysis
        #     ↓
        # MarketRegime
        #     ↓
        # PostgreSQL
        #     ↓
        # Market Condition workspace
        # ====================================================

        migrations.CreateModel(  # OBJECT CREATION / FUNCTION CALL: Creates a Django migration operation for a new database model.
            name='MarketRegime',  # KEYWORD ARGUMENT + STRING: Sets the model name to MarketRegime.
            fields=[  # KEYWORD ARGUMENT + LIST: Defines all database fields belonging to MarketRegime.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # TUPLE + OBJECT: Creates the automatically increasing primary-key ID field.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # TUPLE + DATETIME FIELD: Automatically records when the database row is first created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # TUPLE + DATETIME FIELD: Automatically updates the timestamp whenever the row changes.
                ('symbol', models.CharField(max_length=20)),  # TUPLE + STRING FIELD: Stores a market ticker symbol such as SPY with a maximum of 20 characters.
                ('date', models.DateField()),  # TUPLE + DATE FIELD: Stores the date associated with the detected market regime.
                ('regime', models.CharField(choices=[('bull', 'Bull Market'), ('bear', 'Bear Market'), ('sideways', 'Sideways'), ('volatile', 'High Volatility')], max_length=20)),  # NESTED LIST + TUPLES: Stores one allowed market-regime choice.
                ('confidence', models.DecimalField(decimal_places=6, max_digits=8)),  # DECIMAL FIELD: Stores the confidence level of the market-regime result with controlled numerical precision.
                ('volatility', models.DecimalField(decimal_places=6, max_digits=10)),  # DECIMAL FIELD: Stores the calculated volatility value.
                ('trend_strength', models.DecimalField(decimal_places=6, max_digits=10)),  # DECIMAL FIELD: Stores the calculated strength of the detected market trend.
            ],  # LIST: Ends the MarketRegime field definitions.
            options={  # KEYWORD ARGUMENT + DICTIONARY: Defines additional configuration for the MarketRegime model.
                'ordering': ['-date'],  # DICTIONARY ENTRY + LIST: Orders MarketRegime records by date from newest to oldest.
                'constraints': [models.UniqueConstraint(fields=('symbol', 'date'), name='unique_regime_date')],  # DATABASE CONSTRAINT: Prevents duplicate MarketRegime rows for the same symbol and date.
            },  # DICTIONARY: Ends the MarketRegime model options.
        ),  # OBJECT / OPERATION: Ends the CreateModel operation for MarketRegime.

        # ====================================================
        # 4. CREATE OVERFITTING TEST MODEL
        # ====================================================
        #
        # PURPOSE:
        # Stores the result of testing whether a strategy
        # performs well only on the data used to develop it.
        #
        # MARKETPULSE FLOW:
        #
        # Strategy
        #     ↓
        # Historical Market Data
        #     ↓
        # In-sample test
        #     ↓
        # Out-of-sample test
        #     ↓
        # OverfittingTest
        #     ↓
        # PostgreSQL
        # ====================================================

        migrations.CreateModel(  # OBJECT CREATION / FUNCTION CALL: Creates the database model used to store strategy overfitting-test results.
            name='OverfittingTest',  # KEYWORD ARGUMENT + STRING: Sets the Django model name.
            fields=[  # KEYWORD ARGUMENT + LIST: Begins all fields belonging to OverfittingTest.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # PRIMARY KEY: Creates the automatically generated unique database ID.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # DATETIME FIELD: Records when the overfitting test was first saved.
                ('updated_at', models.DateTimeField(auto_now=True)),  # DATETIME FIELD: Records when the saved test was last updated.
                ('symbol', models.CharField(max_length=20)),  # STRING FIELD: Stores the ticker symbol used by the overfitting test.
                ('test_period', models.CharField(max_length=60)),  # STRING FIELD: Stores a description of the period used for the test.
                ('in_sample_return', models.DecimalField(decimal_places=6, max_digits=10)),  # DECIMAL FIELD: Stores the strategy return on the data used during model development.
                ('out_sample_return', models.DecimalField(decimal_places=6, max_digits=10)),  # DECIMAL FIELD: Stores the strategy return on data outside the development sample.
                ('overfitting_score', models.DecimalField(decimal_places=6, max_digits=10)),  # DECIMAL FIELD: Stores the calculated measure of possible strategy overfitting.
                ('is_overfitted', models.BooleanField(default=False)),  # BOOLEAN FIELD: Stores True or False depending on whether the strategy was classified as overfitted.
                ('recommendations', models.TextField(blank=True)),  # TEXT FIELD: Stores optional recommendations produced from the overfitting analysis.
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overfitting_tests', to='core.strategy')),  # FOREIGN KEY: Links this test to a Strategy and deletes the test if that strategy is deleted.
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overfitting_tests', to=settings.AUTH_USER_MODEL)),  # FOREIGN KEY: Links the test to the user who owns it and follows the configured Django user model.
            ],  # LIST: Ends the OverfittingTest field definitions.
            options={  # KEYWORD ARGUMENT + DICTIONARY: Begins extra model configuration.
                'abstract': False,  # BOOLEAN: States that this is a real concrete model rather than an abstract-only model.
            },  # DICTIONARY: Ends the OverfittingTest options.
        ),  # OBJECT / OPERATION: Ends the CreateModel operation for OverfittingTest.

        # ====================================================
        # 5. CREATE STRESS TEST MODEL
        # ====================================================
        #
        # PURPOSE:
        # Stores results showing how a strategy behaves under
        # difficult or extreme simulated market conditions.
        #
        # TEST TYPES:
        #
        # - Market Crash
        # - Volatility Spike
        # - Liquidity Crisis
        # - Regime Change
        #
        # MARKETPULSE FLOW:
        #
        # Strategy
        #     ↓
        # Selected stress scenario
        #     ↓
        # Stress-test calculation
        #     ↓
        # Max drawdown / Recovery / Robustness
        #     ↓
        # StressTest
        #     ↓
        # PostgreSQL
        # ====================================================

        migrations.CreateModel(  # OBJECT CREATION / FUNCTION CALL: Creates the model used to store strategy stress-test results.
            name='StressTest',  # KEYWORD ARGUMENT + STRING: Sets the Django model name to StressTest.
            fields=[  # KEYWORD ARGUMENT + LIST: Begins the StressTest database field definitions.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # PRIMARY KEY: Creates an automatically increasing unique ID for each stress-test record.
                ('created_at', models.DateTimeField(auto_now_add=True)),  # DATETIME FIELD: Automatically records when the stress-test record is created.
                ('updated_at', models.DateTimeField(auto_now=True)),  # DATETIME FIELD: Automatically records when the stress-test record is updated.
                ('symbol', models.CharField(max_length=20)),  # STRING FIELD: Stores the ticker symbol used by the stress test.
                ('test_type', models.CharField(choices=[('crash', 'Market Crash'), ('volatility_spike', 'Volatility Spike'), ('liquidity_crisis', 'Liquidity Crisis'), ('regime_change', 'Regime Change')], max_length=40)),  # CHOICES + NESTED TUPLES: Restricts the stress-test type to one of four predefined scenarios.
                ('test_parameters', models.JSONField(default=dict)),  # JSON FIELD + DICTIONARY: Stores flexible stress-test parameters as JSON data.
                ('max_drawdown', models.DecimalField(decimal_places=6, max_digits=10)),  # DECIMAL FIELD: Stores the largest decline experienced during the stress scenario.
                ('recovery_time', models.PositiveIntegerField(default=0)),  # INTEGER FIELD: Stores a non-negative recovery-time value and defaults to zero.
                ('robustness_score', models.DecimalField(decimal_places=6, max_digits=10)),  # DECIMAL FIELD: Stores the calculated strategy robustness score.
                ('passed_test', models.BooleanField(default=False)),  # BOOLEAN FIELD: Stores whether the strategy passed the stress test.
                ('notes', models.TextField(blank=True)),  # TEXT FIELD: Stores optional notes about the stress-test result.
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_tests', to='core.strategy')),  # FOREIGN KEY: Connects the stress test to a Strategy and cascades deletion when that Strategy is deleted.
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_tests', to=settings.AUTH_USER_MODEL)),  # FOREIGN KEY: Connects the stress-test result to the configured Django user account.
            ],  # LIST: Ends the StressTest field definitions.
            options={  # KEYWORD ARGUMENT + DICTIONARY: Begins additional StressTest model settings.
                'abstract': False,  # BOOLEAN: Confirms that StressTest is a concrete database-backed model.
            },  # DICTIONARY: Ends the StressTest model options.
        ),  # OBJECT / OPERATION: Ends the CreateModel operation for StressTest.
    ]  # LIST: Ends all database operations performed by this migration.